# Property Data ETL Pipeline

This notebook implements a complete ETL pipeline for property data with:
- Data creation
- File structure setup
- API request and data saving
- Data processing
- Dimension/fact table creation
- PostgreSQL loading
- Orchestration planning
- Monitoring setup
- BI/ML integration

In [507]:
import os
import json
import pandas as pd
import numpy as np
import psycopg2
from sqlalchemy import create_engine
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# !pip install faker
print("All Libraries imported successfully")

All Libraries imported successfully

## 1. Extract Data with

In [508]:
import requests
import json
import os

# API request details
url = "https://api.rentcast.io/v1/properties/random?limit=500"
headers = {
    "accept": "application/json",
    "X-Api-Key": "unsucessful-code"
}

# Request data
response = requests.get(url, headers=headers)

# Check for success before saving
if response.status_code == 200:
    data = response.json()

    # Ensure RawData folder exists
    os.makedirs("RawData", exist_ok=True)

    # Save the file
    filename = "data/raw/propertyrecords01.json"
    with open(filename, 'w') as file:
        json.dump(data, file, indent=4)
        print(f"✅ File saved as: {filename}")

else:
    print(f"❌ Failed to fetch data: {response.status_code} - {response.text}")

❌ Failed to fetch data: 401 - {"status":401,"error":"auth/api-key-invalid","message":"The provided API key is not valid. Manage API keys on your API dashboard: https://app.rentcast.io/app/api"}

## 2. File/Folder Structure for ETL Pipeline

In [509]:
def create_folder_structure():
    folders = [
        'data/raw',
        'data/processed',
        'data/dimensions',
        'data/facts',
        'scripts',
        'logs',
        'tests',
        'dags',  # For Airflow
        'notebooks',
        'reports',
        'models'
    ]
    
    for folder in folders:
        os.makedirs(folder, exist_ok=True)
        print(f"Created folder: {folder}")
    
    # Create empty __init__.py files to make folders Python packages
    with open('scripts/__init__.py', 'w') as f:
        pass
    with open('tests/__init__.py', 'w') as f:
        pass

create_folder_structure()

Created folder: data/raw
Created folder: data/processed
Created folder: data/dimensions
Created folder: data/facts
Created folder: scripts
Created folder: logs
Created folder: tests
Created folder: dags
Created folder: notebooks
Created folder: reports
Created folder: models

## 3. Save Sample Data as JSON (Simulating API Response)
- saved sample datas as "data/raw/propertyrecords01", "data/raw/propertyrecords02" etc
- combine sample datas "data/raw/propertyrecords01", "data/raw/propertyrecords02" etc to make "data/raw/propertyrecords"
- load the JSON "data/raw/propertyrecords" into propertyrecords_df

In [510]:
    
'''
# API request details
url = "https://api.rentcast.io/v1/properties/random?limit=500"
headers = {
    "accept": "application/json",
    "X-Api-Key": "put-in-the-write-api"
}

# Request data
response = requests.get(url, headers=headers)

# Check for success before saving
if response.status_code == 200:
    data = response.json()

    # Ensure data/raw directory exists
    os.makedirs("data/raw", exist_ok=True)

    # Save the file with sequential numbering
    filename = f"data/raw/propertyrecords{file_number:02d}.json"
    with open(filename, 'w') as file:
        json.dump(data, file, indent=4)
        print(f"✅ File saved as: {filename}")

else:
    print(f"❌ Failed to fetch data: {response.status_code} - {response.text}")
    
    


# Get all propertyrecords files
input_files = Path('data/raw').glob('propertyrecords*.json')
combined_data = []

# Read and combine the records
for file in input_files:
    with open(file, 'r') as f:
        data = json.load(f)
        combined_data.extend(data)  # assumes each file contains a list of records

# Write the combined data into Records.json
with open('data/raw/property_records.json', 'w') as outfile:
    json.dump(combined_data, outfile, indent=4)

print("✅ Successfully combined into 'data/raw/property_records.json'")
    
'''


# Load the data
with open('data/raw/property_records.json') as f:
    data = json.load(f)

propertyrecords_df = pd.DataFrame(data)

print("propertyrecords_df is loaded")

propertyrecords_df is loaded

In [511]:
# Print Out Datytypes of each column
print("\n=== Data Types by Column ===")
for col in propertyrecords_df.columns:
    print(f"{col}: {propertyrecords_df[col].dtype}")

=== Data Types by Column ===
id: object
formattedAddress: object
addressLine1: object
addressLine2: object
city: object
state: object
zipCode: object
county: object
latitude: float64
longitude: float64
propertyType: object
bedrooms: float64
bathrooms: float64
squareFootage: float64
lotSize: float64
yearBuilt: float64
assessorID: object
legalDescription: object
subdivision: object
lastSaleDate: object
features: object
taxAssessments: object
propertyTaxes: object
owner: object
ownerOccupied: object
zoning: object
lastSalePrice: float64
history: object
hoa: object

## 4. Data Pre-processing Checks

In [512]:
def preprocess_checking():
    # Initial checks
    print("=== Initial Data Shape ===")
    print(propertyrecords_df.shape)

    print("\n=== Data Types ===")
    print(propertyrecords_df.dtypes)

    print("\n=== Null Values ===")
    print(propertyrecords_df.isnull().sum())

    # Select only columns that can safely use nunique()
    # numeric_cols = propertyrecords_df.select_dtypes(include=['int', 'float', 'category', 'object']).columns
    # property_std[numeric_cols].nunique()
    # property_std.nunique() # Get Unique Value Counts per Column

    # Unhashable columns that needes to be flattened out
    print("\n=== Unique Values Vs Dist/List ===")
    for col in propertyrecords_df.columns:
        try:
            print(f"{col}: {propertyrecords_df[col].nunique()} unique values")
        except TypeError:
            print(f"{col}: Contains unhashable type (e.g., dict/list)")
    return propertyrecords_df

preprocess_checking()

=== Initial Data Shape ===
(5500, 29)

=== Data Types ===
id                   object
formattedAddress     object
addressLine1         object
addressLine2         object
city                 object
state                object
zipCode              object
county               object
latitude            float64
longitude           float64
propertyType         object
bedrooms            float64
bathrooms           float64
squareFootage       float64
lotSize             float64
yearBuilt           float64
assessorID           object
legalDescription     object
subdivision          object
lastSaleDate         object
features             object
taxAssessments       object
propertyTaxes        object
owner                object
ownerOccupied        object
zoning               object
lastSalePrice       float64
history              object
hoa                  object
dtype: object

=== Null Values ===
id                     0
formattedAddress       0
addressLine1           0
addressLine2        4327
city                   0
state                  0
zipCode                0
county                 4
latitude               0
longitude              0
propertyType         990
bedrooms            1789
bathrooms           1459
squareFootage       1251
lotSize             1542
yearBuilt           1385
assessorID          1513
legalDescription    1603
subdivision         2100
lastSaleDate        1998
features            1619
taxAssessments      1586
propertyTaxes       1669
owner               1568
ownerOccupied       1568
zoning              3478
lastSalePrice       2700
history             2943
hoa                 5402
dtype: int64

=== Unique Values Vs Dist/List ===
id: 4498 unique values
formattedAddress: 4498 unique values
addressLine1: 4496 unique values
addressLine2: 625 unique values
city: 1928 unique values
state: 51 unique values
zipCode: 3423 unique values
county: 798 unique values
latitude: 4496 unique values
longitude: 4495 unique values
propertyType: 7 unique values
bedrooms: 12 unique values
bathrooms: 15 unique values
squareFootage: 1825 unique values
lotSize: 1820 unique values
yearBuilt: 151 unique values
assessorID: 3265 unique values
legalDescription: 3180 unique values
subdivision: 2701 unique values
lastSaleDate: 2222 unique values
features: Contains unhashable type (e.g., dict/list)
taxAssessments: Contains unhashable type (e.g., dict/list)
propertyTaxes: Contains unhashable type (e.g., dict/list)
owner: Contains unhashable type (e.g., dict/list)
ownerOccupied: 2 unique values
zoning: 692 unique values
lastSalePrice: 1143 unique values
history: Contains unhashable type (e.g., dict/list)
hoa: Contains unhashable type (e.g., dict/list)

,id,formattedAddress,addressLine1,addressLine2,city,state,zipCode,county,latitude,longitude,...,lastSaleDate,features,taxAssessments,propertyTaxes,owner,ownerOccupied,zoning,lastSalePrice,history,hoa
0,"82-Nw-5th-Ave,-Apt-9,-Delray-Beach,-FL-33444","82 Nw 5th Ave, Apt 9, Delray Beach, FL 33444",82 Nw 5th Ave,Apt 9,Delray Beach,FL,33444,Palm Beach,26.463107,-80.078482,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"PO-Box-219187,-Houston,-TX-77218","PO Box 219187, Houston, TX 77218",PO Box 219187,None,Houston,TX,77218,Harris,29.784900,-95.675000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"2210-W-Canyon-Dr,-Coeur-D-Alene,-ID-83815","2210 W Canyon Dr, Coeur D Alene, ID 83815",2210 W Canyon Dr,None,Coeur D Alene,ID,83815,Kootenai,47.711100,-116.818306,...,1995-02-01T00:00:00.000Z,"{'cooling': True, 'fireplace': True, 'floorCou...","{'2020': {'year': 2020, 'value': 329206, 'land...","{'2020': {'year': 2020, 'total': 2054}, '2022'...","{'names': ['TALBOT ANTHONY G M ETUX'], 'mailin...",True,NaN,NaN,NaN,NaN
3,"11650-W-Bellfort-Ave,-Apt-809,-Houston,-TX-77099","11650 W Bellfort Ave, Apt 809, Houston, TX 77099",11650 W Bellfort Ave,Apt 809,Houston,TX,77099,Harris,29.658933,-95.582056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"801-Plate-St,-Unit-206,-Rochester,-MI-48307","801 Plate St, Unit 206, Rochester, MI 48307",801 Plate St,Unit 206,Rochester,MI,48307,Oakland,42.687461,-83.125512,...,2023-10-10T00:00:00.000Z,"{'exteriorType': 'Brick', 'fireplace': True, '...","{'2023': {'year': 2023, 'value': 43210}}","{'2021': {'year': 2021, 'total': 1013}}","{'names': ['Majed Sayedah'], 'type': 'Individu...",False,KI,119222.0,"{'2023-10-10': {'event': 'Sale', 'date': '2023...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,"10231-Copperwood-Dr,-Houston,-TX-77040","10231 Copperwood Dr, Houston, TX 77040",10231 Copperwood Dr,None,Houston,TX,77040,Harris,29.889569,-95.505145,...,NaN,"{'architectureType': 'Traditional', 'cooling':...","{'2022': {'year': 2022, 'value': 180560, 'land...","{'2020': {'year': 2020, 'total': 29}, '2022': ...","{'names': ['Paul J Wieting', 'Peggy J Wieting'...",True,NaN,NaN,NaN,NaN
5496,"1030-E-Lancaster-Ave,-Apt-819,-Bryn-Mawr,-PA-1...","1030 E Lancaster Ave, Apt 819, Bryn Mawr, PA 1...",1030 E Lancaster Ave,Apt 819,Bryn Mawr,PA,19010,Delaware,40.028230,-75.331276,...,2012-01-25T00:00:00.000Z,"{'architectureType': 'Condo / Apartment', 'ext...","{'2018': {'year': 2018, 'value': 69650}, '2019...","{'2018': {'year': 2018, 'total': 2308}, '2019'...","{'names': ['CHRISTOPHER A DIPASQUA'], 'mailing...",False,NaN,19800.0,"{'2012-01-25': {'event': 'Sale', 'date': '2012...",NaN
5497,"4315-N-Browning-Dr,-West-Palm-Beach,-FL-33406","4315 N Browning Dr, West Palm Beach, FL 33406",4315 N Browning Dr,None,West Palm Beach,FL,33406,Palm Beach,26.676598,-80.109007,...,1986-08-01T00:00:00.000Z,"{'cooling': True, 'coolingType': 'Commercial',...","{'2022': {'year': 2022, 'value': 62377}}","{'2022': {'year': 2022, 'total': 1017}}","{'names': ['LOUISE E STUMP'], 'mailingAddress'...",True,RM,57000.0,NaN,NaN
5498,"13162-Dunwick-Rd,-Jacksonville,-FL-32256","13162 Dunwick Rd, Jacksonville, FL 32256",13162 Dunwick Rd,None,Jacksonville,FL,32256,Duval,30.143313,-81.491554,...,2022-10-31T00:00:00.000Z,"{'cooling': True, 'coolingType': 'Central', 'e...","{'2022': {'year': 2022, 'value': 70000, 'land'...","{'2022': {'year': 2022, 'total': 1192}, '2023'...","{'names': ['Phillip Michael Justice', 'Ashlyn ...",True,PUD,542500.0,"{'2022-10-31': {'event': 'Sale', 'date': '2022...",NaN
5499,"14039-Guadalupe-Pass,-San-Antonio,-TX-78253","14039 Guadalupe Pass, San Antonio, TX 78253",14039 Guadalupe Pass,None,San Antonio,TX,78253,Bexar,29.480368,-98.773793,...,2023-03-31T00:00:00.000Z,"{'cooling': True, 'coolingType': 'Central', 'f...","{'2023': {'year': 2023, 'value': 254000, 'land...","{'2023': {'year': 2023, 'total': 5139}}","{'names': ['Anna Luisa Robles Sanchez', 'Berna...",True,NaN,NaN,"{'2023-03-31': {'event': 'Sale', 'date': '2023...",NaN

## 5. Standardize Column Names

In [513]:
def standardize_column_names():
    # Standardize column names (snake_case to snake_case here, but could convert from camelCase if needed)
    #propertyrecords_df.columns = [col.lower() for col in propertyrecords_df.columns]
    #print("Standardized column names:", propertyrecords_df.columns.tolist())

    propertyrecords_df.columns = [col.lower() for col in propertyrecords_df.columns]

    propertyrecords_df.rename(columns={
        'zipcode': 'zip_code',
        'squarefootage': 'square_footage',
        'lotsize': 'lot_size',
        'yearbuilt': 'year_built',
        'assessorid': 'assessor_id',
        'legaldescription': 'legal_description',
        'lastsaledate': 'last_sale_date',
        'lastsaleprice': 'last_sale_price',
        'propertytaxes': 'property_taxes',
        'taxassessments': 'tax_assessments',
        'formattedaddress': 'formatted_address',
        'propertytype': 'property_type',
        'addressline1': 'address_line1',
        'addressline2': 'address_line2',
        'owneroccupied': 'owner_occupied',
        'hoa': 'hoa_fees'
    }, inplace=True)

    propertyrecords_df.columns

    print("\n=== Data Types by Column ===")
    for col in propertyrecords_df.columns:
        print(f"{col}: {propertyrecords_df[col].dtype}")
    return propertyrecords_df

standardize_column_names()

=== Data Types by Column ===
id: object
formatted_address: object
address_line1: object
address_line2: object
city: object
state: object
zip_code: object
county: object
latitude: float64
longitude: float64
property_type: object
bedrooms: float64
bathrooms: float64
square_footage: float64
lot_size: float64
year_built: float64
assessor_id: object
legal_description: object
subdivision: object
last_sale_date: object
features: object
tax_assessments: object
property_taxes: object
owner: object
owner_occupied: object
zoning: object
last_sale_price: float64
history: object
hoa_fees: object

,id,formatted_address,address_line1,address_line2,city,state,zip_code,county,latitude,longitude,...,last_sale_date,features,tax_assessments,property_taxes,owner,owner_occupied,zoning,last_sale_price,history,hoa_fees
0,"82-Nw-5th-Ave,-Apt-9,-Delray-Beach,-FL-33444","82 Nw 5th Ave, Apt 9, Delray Beach, FL 33444",82 Nw 5th Ave,Apt 9,Delray Beach,FL,33444,Palm Beach,26.463107,-80.078482,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"PO-Box-219187,-Houston,-TX-77218","PO Box 219187, Houston, TX 77218",PO Box 219187,None,Houston,TX,77218,Harris,29.784900,-95.675000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"2210-W-Canyon-Dr,-Coeur-D-Alene,-ID-83815","2210 W Canyon Dr, Coeur D Alene, ID 83815",2210 W Canyon Dr,None,Coeur D Alene,ID,83815,Kootenai,47.711100,-116.818306,...,1995-02-01T00:00:00.000Z,"{'cooling': True, 'fireplace': True, 'floorCou...","{'2020': {'year': 2020, 'value': 329206, 'land...","{'2020': {'year': 2020, 'total': 2054}, '2022'...","{'names': ['TALBOT ANTHONY G M ETUX'], 'mailin...",True,NaN,NaN,NaN,NaN
3,"11650-W-Bellfort-Ave,-Apt-809,-Houston,-TX-77099","11650 W Bellfort Ave, Apt 809, Houston, TX 77099",11650 W Bellfort Ave,Apt 809,Houston,TX,77099,Harris,29.658933,-95.582056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"801-Plate-St,-Unit-206,-Rochester,-MI-48307","801 Plate St, Unit 206, Rochester, MI 48307",801 Plate St,Unit 206,Rochester,MI,48307,Oakland,42.687461,-83.125512,...,2023-10-10T00:00:00.000Z,"{'exteriorType': 'Brick', 'fireplace': True, '...","{'2023': {'year': 2023, 'value': 43210}}","{'2021': {'year': 2021, 'total': 1013}}","{'names': ['Majed Sayedah'], 'type': 'Individu...",False,KI,119222.0,"{'2023-10-10': {'event': 'Sale', 'date': '2023...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,"10231-Copperwood-Dr,-Houston,-TX-77040","10231 Copperwood Dr, Houston, TX 77040",10231 Copperwood Dr,None,Houston,TX,77040,Harris,29.889569,-95.505145,...,NaN,"{'architectureType': 'Traditional', 'cooling':...","{'2022': {'year': 2022, 'value': 180560, 'land...","{'2020': {'year': 2020, 'total': 29}, '2022': ...","{'names': ['Paul J Wieting', 'Peggy J Wieting'...",True,NaN,NaN,NaN,NaN
5496,"1030-E-Lancaster-Ave,-Apt-819,-Bryn-Mawr,-PA-1...","1030 E Lancaster Ave, Apt 819, Bryn Mawr, PA 1...",1030 E Lancaster Ave,Apt 819,Bryn Mawr,PA,19010,Delaware,40.028230,-75.331276,...,2012-01-25T00:00:00.000Z,"{'architectureType': 'Condo / Apartment', 'ext...","{'2018': {'year': 2018, 'value': 69650}, '2019...","{'2018': {'year': 2018, 'total': 2308}, '2019'...","{'names': ['CHRISTOPHER A DIPASQUA'], 'mailing...",False,NaN,19800.0,"{'2012-01-25': {'event': 'Sale', 'date': '2012...",NaN
5497,"4315-N-Browning-Dr,-West-Palm-Beach,-FL-33406","4315 N Browning Dr, West Palm Beach, FL 33406",4315 N Browning Dr,None,West Palm Beach,FL,33406,Palm Beach,26.676598,-80.109007,...,1986-08-01T00:00:00.000Z,"{'cooling': True, 'coolingType': 'Commercial',...","{'2022': {'year': 2022, 'value': 62377}}","{'2022': {'year': 2022, 'total': 1017}}","{'names': ['LOUISE E STUMP'], 'mailingAddress'...",True,RM,57000.0,NaN,NaN
5498,"13162-Dunwick-Rd,-Jacksonville,-FL-32256","13162 Dunwick Rd, Jacksonville, FL 32256",13162 Dunwick Rd,None,Jacksonville,FL,32256,Duval,30.143313,-81.491554,...,2022-10-31T00:00:00.000Z,"{'cooling': True, 'coolingType': 'Central', 'e...","{'2022': {'year': 2022, 'value': 70000, 'land'...","{'2022': {'year': 2022, 'total': 1192}, '2023'...","{'names': ['Phillip Michael Justice', 'Ashlyn ...",True,PUD,542500.0,"{'2022-10-31': {'event': 'Sale', 'date': '2022...",NaN
5499,"14039-Guadalupe-Pass,-San-Antonio,-TX-78253","14039 Guadalupe Pass, San Antonio, TX 78253",14039 Guadalupe Pass,None,San Antonio,TX,78253,Bexar,29.480368,-98.773793,...,2023-03-31T00:00:00.000Z,"{'cooling': True, 'coolingType': 'Central', 'f...","{'2023': {'year': 2023, 'value': 254000, 'land...","{'2023': {'year': 2023, 'total': 5139}}","{'names': ['Anna Luisa Robles Sanchez', 'Berna...",True,NaN,NaN,"{'2023-03-31': {'event': 'Sale', 'date': '2023...",NaN

In [514]:

def check_expected_columns():
    # List out your expected columns and verify they are not missing
    expected_columns = [
        'id', 'address_line1', 'address_line2', 'city', 'state', 'zip_code',
        'county', 'latitude', 'longitude', 'property_type', 'bedrooms',
        'bathrooms', 'square_footage', 'lot_size', 'year_built', 'assessor_id',
        'legal_description', 'subdivision', 'zoning', 'owner_occupied'
    ]

    # Check which ones are missing
    missing_cols = [col for col in expected_columns if col not in propertyrecords_df.columns]
    print("❌ Missing columns:", missing_cols)
check_expected_columns()

❌ Missing columns: []

In [515]:
def assert_expected_columns():
    # Verify all expected columns are present in the propertyrecords_df

    expected_columns = [
        'id', 'address_line1', 'address_line2', 'city', 'state', 'zip_code',
        'county', 'latitude', 'longitude', 'property_type', 'bedrooms',
        'bathrooms', 'square_footage', 'lot_size', 'year_built', 'assessor_id',
        'legal_description', 'subdivision', 'zoning', 'owner_occupied'
    ]

    # Identify missing columns
    missing_cols = [col for col in expected_columns if col not in propertyrecords_df.columns]

    # Assert no columns are missing
    assert not missing_cols, f"❌ Missing columns: {missing_cols}"

    print("✅ All expected columns are present!")
    
assert_expected_columns()

✅ All expected columns are present!

## 6. Flatten Unhashable Data

In [516]:
def flaten_unhashable_data():
    # Flatten features
    # features_df = pd.json_normalize(propertyrecords_df['features'])
    # features_df.columns = [f"feature_{col}" for col in features_df.columns]
    # propertyrecords_df = pd.concat([propertyrecords_df.drop('features', axis=1), features_df], axis=1)


    print("===========JSON data parameters before being flattened out=================")
    for col in propertyrecords_df.columns:
        try:
            print(f"{col}: {propertyrecords_df[col].nunique()} unique values")
        except TypeError:
            print(f"{col}: Contains unhashable type (e.g., dict/list)")


    # Convert the nested json data parameter features into strings or flatten it out

    propertyrecords_df['features'] = propertyrecords_df['features'].apply(json.dumps)

    propertyrecords_df['tax_assessments'] = propertyrecords_df['tax_assessments'].apply(json.dumps)
    propertyrecords_df['property_taxes'] = propertyrecords_df['property_taxes'].apply(json.dumps)
    propertyrecords_df['hoa_fees'] = propertyrecords_df['hoa_fees'].apply(json.dumps)
    propertyrecords_df['owner'] = propertyrecords_df['owner'].apply(json.dumps)
    propertyrecords_df['history'] = propertyrecords_df['history'].apply(json.dumps)

    # propertyrecords_df['subdivision'] = propertyrecords_df['subdivision'].apply(json.dumps)
    # propertyrecords_df['assessorID'] = propertyrecords_df['assessorID'].apply(json.dumps)
    # propertyrecords_df['legal_description'] = propertyrecords_df['legal_description'].apply(json.dumps)
    # propertyrecords_df['zoning'] = propertyrecords_df['zoning'].apply(json.dumps)


    print("===========JSON data parameters flattened out=================")

    for col in propertyrecords_df.columns:
        try:
            print(f"{col}: {propertyrecords_df[col].nunique()} unique values")
        except TypeError:
            print(f"{col}: Contains unhashable type (e.g., dict/list)")
            
    return propertyrecords_df

flaten_unhashable_data()

===========JSON data parameters before being flattened out=================
id: 4498 unique values
formatted_address: 4498 unique values
address_line1: 4496 unique values
address_line2: 625 unique values
city: 1928 unique values
state: 51 unique values
zip_code: 3423 unique values
county: 798 unique values
latitude: 4496 unique values
longitude: 4495 unique values
property_type: 7 unique values
bedrooms: 12 unique values
bathrooms: 15 unique values
square_footage: 1825 unique values
lot_size: 1820 unique values
year_built: 151 unique values
assessor_id: 3265 unique values
legal_description: 3180 unique values
subdivision: 2701 unique values
last_sale_date: 2222 unique values
features: Contains unhashable type (e.g., dict/list)
tax_assessments: Contains unhashable type (e.g., dict/list)
property_taxes: Contains unhashable type (e.g., dict/list)
owner: Contains unhashable type (e.g., dict/list)
owner_occupied: 2 unique values
zoning: 692 unique values
last_sale_price: 1143 unique values
history: Contains unhashable type (e.g., dict/list)
hoa_fees: Contains unhashable type (e.g., dict/list)
===========JSON data parameters flattened out=================
id: 4498 unique values
formatted_address: 4498 unique values
address_line1: 4496 unique values
address_line2: 625 unique values
city: 1928 unique values
state: 51 unique values
zip_code: 3423 unique values
county: 798 unique values
latitude: 4496 unique values
longitude: 4495 unique values
property_type: 7 unique values
bedrooms: 12 unique values
bathrooms: 15 unique values
square_footage: 1825 unique values
lot_size: 1820 unique values
year_built: 151 unique values
assessor_id: 3265 unique values
legal_description: 3180 unique values
subdivision: 2701 unique values
last_sale_date: 2222 unique values
features: 2770 unique values
tax_assessments: 3199 unique values
property_taxes: 3128 unique values
owner: 3204 unique values
owner_occupied: 2 unique values
zoning: 692 unique values
last_sale_price: 1143 unique values
history: 2058 unique values
hoa_fees: 67 unique values

,id,formatted_address,address_line1,address_line2,city,state,zip_code,county,latitude,longitude,...,last_sale_date,features,tax_assessments,property_taxes,owner,owner_occupied,zoning,last_sale_price,history,hoa_fees
0,"82-Nw-5th-Ave,-Apt-9,-Delray-Beach,-FL-33444","82 Nw 5th Ave, Apt 9, Delray Beach, FL 33444",82 Nw 5th Ave,Apt 9,Delray Beach,FL,33444,Palm Beach,26.463107,-80.078482,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"PO-Box-219187,-Houston,-TX-77218","PO Box 219187, Houston, TX 77218",PO Box 219187,None,Houston,TX,77218,Harris,29.784900,-95.675000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"2210-W-Canyon-Dr,-Coeur-D-Alene,-ID-83815","2210 W Canyon Dr, Coeur D Alene, ID 83815",2210 W Canyon Dr,None,Coeur D Alene,ID,83815,Kootenai,47.711100,-116.818306,...,1995-02-01T00:00:00.000Z,"{""cooling"": true, ""fireplace"": true, ""floorCou...","{""2020"": {""year"": 2020, ""value"": 329206, ""land...","{""2020"": {""year"": 2020, ""total"": 2054}, ""2022""...","{""names"": [""TALBOT ANTHONY G M ETUX""], ""mailin...",True,NaN,NaN,NaN,NaN
3,"11650-W-Bellfort-Ave,-Apt-809,-Houston,-TX-77099","11650 W Bellfort Ave, Apt 809, Houston, TX 77099",11650 W Bellfort Ave,Apt 809,Houston,TX,77099,Harris,29.658933,-95.582056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"801-Plate-St,-Unit-206,-Rochester,-MI-48307","801 Plate St, Unit 206, Rochester, MI 48307",801 Plate St,Unit 206,Rochester,MI,48307,Oakland,42.687461,-83.125512,...,2023-10-10T00:00:00.000Z,"{""exteriorType"": ""Brick"", ""fireplace"": true, ""...","{""2023"": {""year"": 2023, ""value"": 43210}}","{""2021"": {""year"": 2021, ""total"": 1013}}","{""names"": [""Majed Sayedah""], ""type"": ""Individu...",False,KI,119222.0,"{""2023-10-10"": {""event"": ""Sale"", ""date"": ""2023...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,"10231-Copperwood-Dr,-Houston,-TX-77040","10231 Copperwood Dr, Houston, TX 77040",10231 Copperwood Dr,None,Houston,TX,77040,Harris,29.889569,-95.505145,...,NaN,"{""architectureType"": ""Traditional"", ""cooling"":...","{""2022"": {""year"": 2022, ""value"": 180560, ""land...","{""2020"": {""year"": 2020, ""total"": 29}, ""2022"": ...","{""names"": [""Paul J Wieting"", ""Peggy J Wieting""...",True,NaN,NaN,NaN,NaN
5496,"1030-E-Lancaster-Ave,-Apt-819,-Bryn-Mawr,-PA-1...","1030 E Lancaster Ave, Apt 819, Bryn Mawr, PA 1...",1030 E Lancaster Ave,Apt 819,Bryn Mawr,PA,19010,Delaware,40.028230,-75.331276,...,2012-01-25T00:00:00.000Z,"{""architectureType"": ""Condo / Apartment"", ""ext...","{""2018"": {""year"": 2018, ""value"": 69650}, ""2019...","{""2018"": {""year"": 2018, ""total"": 2308}, ""2019""...","{""names"": [""CHRISTOPHER A DIPASQUA""], ""mailing...",False,NaN,19800.0,"{""2012-01-25"": {""event"": ""Sale"", ""date"": ""2012...",NaN
5497,"4315-N-Browning-Dr,-West-Palm-Beach,-FL-33406","4315 N Browning Dr, West Palm Beach, FL 33406",4315 N Browning Dr,None,West Palm Beach,FL,33406,Palm Beach,26.676598,-80.109007,...,1986-08-01T00:00:00.000Z,"{""cooling"": true, ""coolingType"": ""Commercial"",...","{""2022"": {""year"": 2022, ""value"": 62377}}","{""2022"": {""year"": 2022, ""total"": 1017}}","{""names"": [""LOUISE E STUMP""], ""mailingAddress""...",True,RM,57000.0,NaN,NaN
5498,"13162-Dunwick-Rd,-Jacksonville,-FL-32256","13162 Dunwick Rd, Jacksonville, FL 32256",13162 Dunwick Rd,None,Jacksonville,FL,32256,Duval,30.143313,-81.491554,...,2022-10-31T00:00:00.000Z,"{""cooling"": true, ""coolingType"": ""Central"", ""e...","{""2022"": {""year"": 2022, ""value"": 70000, ""land""...","{""2022"": {""year"": 2022, ""total"": 1192}, ""2023""...","{""names"": [""Phillip Michael Justice"", ""Ashlyn ...",True,PUD,542500.0,"{""2022-10-31"": {""event"": ""Sale"", ""date"": ""2022...",NaN
5499,"14039-Guadalupe-Pass,-San-Antonio,-TX-78253","14039 Guadalupe Pass, San Antonio, TX 78253",14039 Guadalupe Pass,None,San Antonio,TX,78253,Bexar,29.480368,-98.773793,...,2023-03-31T00:00:00.000Z,"{""cooling"": true, ""coolingType"": ""Central"", ""f...","{""2023"": {""year"": 2023, ""value"": 254000, ""land...","{""2023"": {""year"": 2023, ""total"": 5139}}","{""names"": [""Anna Luisa Robles Sanchez"", ""Berna...",True,NaN,NaN,"{""2023-03-31"": {""event"": ""Sale"", ""date"": ""2023...",NaN

## 7. Handle Null Values (fillna or dropna)
- fillup 
- remove critical null rows

In [517]:
def transformation_for_nulls():
    # Remove rows missing critical information
    # critical_cols = ['id', 'formatted_address', 'latitude', 'longitude', 'property_type']
    # propertyrecords_df = propertyrecords_df.dropna(subset=critical_cols)

    #  print("Shape after removing critical null rows:", propertyrecords_df.shape)


    #Transformation Layer
    # 1st step is to convert dictionary to string
    propertyrecords_df['features'] = propertyrecords_df['features'].apply(json.dumps)
    print("Data dictionaries are flattened out")


    # Check missing values
    print("======== Missing values before handling:==========")
    print("Shape before removing critical null rows:", propertyrecords_df.shape)
    print(propertyrecords_df.isnull().sum())


    # Reframe fillna with robust field handling and consistent types
    propertyrecords_df.dropna(subset=['last_sale_price'], inplace=True)  # last_sale_price is critical
    propertyrecords_df.dropna(subset=['tax_assessments'], inplace=True)  # drop row without tax_assessment

    propertyrecords_df.fillna({
        'address_line2': 'Unknown',  # Optional text field
        'county': 'Unknown',  # Could later be inferred from similar `address_line1` or ZIP
        'property_type': 'Unknown',  # Categorical text field
        'lot_size': propertyrecords_df['lot_size'].median(),  # Numeric, use median for balance
        'bedrooms': propertyrecords_df['bedrooms'].median(),  # Numeric field
        'bathrooms': propertyrecords_df['bathrooms'].median(),  # Numeric field
        'square_footage': propertyrecords_df['square_footage'].median(),  # Numeric field
        'year_built': int(propertyrecords_df['year_built'].mode().iloc[0]),  # Using mode now
        'assessor_id': 'Unknown',  # Optional identifier
        'legal_description': 'Unknown',  # Long text — safe to use placeholder
        'subdivision': 'Unknown',  # Categorical grouping
        'last_sale_date': propertyrecords_df['last_sale_date'].mode().iloc[0],  # Use modal date
        'features': 'Unknown',  # Semi-structured text
        'property_taxes': 0,  # Use 0 instead of string if column is numeric, else "Unknown"
        'owner': 'Unknown',  # Owner name
        'owner_occupied': 'Unknown',  # Could be Boolean — double check
        'history': 'Unknown',  # Optional detail
        'zoning': 'Unknown',  # Category for land use
        'hoa_fees': 0  # Assume 0 if not provided
    }, inplace=True)

    print("\n======Missing values after handling:=======")
    print(propertyrecords_df.isnull().sum())           
    print("Shape after removing critical null rows:", propertyrecords_df.shape)
    return propertyrecords_df


transformation_for_nulls()

Data dictionaries are flattened out
======== Missing values before handling:==========
Shape before removing critical null rows: (5500, 29)
id                      0
formatted_address       0
address_line1           0
address_line2        4327
city                    0
state                   0
zip_code                0
county                  4
latitude                0
longitude               0
property_type         990
bedrooms             1789
bathrooms            1459
square_footage       1251
lot_size             1542
year_built           1385
assessor_id          1513
legal_description    1603
subdivision          2100
last_sale_date       1998
features                0
tax_assessments         0
property_taxes          0
owner                   0
owner_occupied       1568
zoning               3478
last_sale_price      2700
history                 0
hoa_fees                0
dtype: int64

======Missing values after handling:=======
id                   0
formatted_address    0
address_line1        0
address_line2        0
city                 0
state                0
zip_code             0
county               0
latitude             0
longitude            0
property_type        0
bedrooms             0
bathrooms            0
square_footage       0
lot_size             0
year_built           0
assessor_id          0
legal_description    0
subdivision          0
last_sale_date       0
features             0
tax_assessments      0
property_taxes       0
owner                0
owner_occupied       0
zoning               0
last_sale_price      0
history              0
hoa_fees             0
dtype: int64
Shape after removing critical null rows: (2800, 29)

,id,formatted_address,address_line1,address_line2,city,state,zip_code,county,latitude,longitude,...,last_sale_date,features,tax_assessments,property_taxes,owner,owner_occupied,zoning,last_sale_price,history,hoa_fees
4,"801-Plate-St,-Unit-206,-Rochester,-MI-48307","801 Plate St, Unit 206, Rochester, MI 48307",801 Plate St,Unit 206,Rochester,MI,48307,Oakland,42.687461,-83.125512,...,2023-10-10T00:00:00.000Z,"""{\""exteriorType\"": \""Brick\"", \""fireplace\"": ...","{""2023"": {""year"": 2023, ""value"": 43210}}","{""2021"": {""year"": 2021, ""total"": 1013}}","{""names"": [""Majed Sayedah""], ""type"": ""Individu...",False,KI,119222.0,"{""2023-10-10"": {""event"": ""Sale"", ""date"": ""2023...",NaN
5,"11328-Van-Buren-St-NE,-Minneapolis,-MN-55434","11328 Van Buren St NE, Minneapolis, MN 55434",11328 Van Buren St NE,Unknown,Minneapolis,MN,55434,Anoka,45.176130,-93.250083,...,2015-05-19T00:00:00.000Z,"""{\""architectureType\"": \""Bi-Level\"", \""coolin...","{""2019"": {""year"": 2019, ""value"": 254200, ""land...","{""2019"": {""year"": 2019, ""total"": 2668}, ""2023""...","{""names"": [""Benjamin Leisen"", ""Amanda Leisen""]...",True,Unknown,239900.0,"{""2015-05-19"": {""event"": ""Sale"", ""date"": ""2015...",NaN
6,"1148-S-Ventura-Cir,-Unit-H,-Aurora,-CO-80017","1148 S Ventura Cir, Unit H, Aurora, CO 80017",1148 S Ventura Cir,Unit H,Aurora,CO,80017,Arapahoe,39.695339,-104.776629,...,2023-05-17T00:00:00.000Z,"""{\""architectureType\"": \""Ranch\"", \""exteriorT...","{""2019"": {""year"": 2019, ""value"": 12699}, ""2020...","{""2019"": {""year"": 2019, ""total"": 1315}, ""2021""...","{""names"": [""Aaron Ward""], ""type"": ""Individual""...",True,PUD,308000.0,"{""2023-05-17"": {""event"": ""Sale"", ""date"": ""2023...",NaN
9,"135-Bordentown-Crosswicks-Rd,-Crosswicks,-NJ-0...","135 Bordentown Crosswicks Rd, Crosswicks, NJ 0...",135 Bordentown Crosswicks Rd,Unknown,Crosswicks,NJ,08515,Burlington,40.144733,-74.663560,...,2009-08-19T00:00:00.000Z,"""{\""unitCount\"": 1, \""architectureType\"": \""Co...","{""2022"": {""year"": 2022, ""value"": 57800, ""land""...","{""2021"": {""year"": 2021, ""total"": 1787}}","{""names"": [""Matthew D Devito""], ""mailingAddres...",True,PVD2,57810.0,NaN,NaN
10,"7700-E-Princess-Dr,-Unit-17,-Scottsdale,-AZ-85255","7700 E Princess Dr, Unit 17, Scottsdale, AZ 85255",7700 E Princess Dr,Unit 17,Scottsdale,AZ,85255,Maricopa,33.645192,-111.913378,...,2022-04-01T00:00:00.000Z,"""{\""cooling\"": true, \""coolingType\"": \""Refrig...","{""2022"": {""year"": 2022, ""value"": 44630, ""land""...","{""2021"": {""year"": 2021, ""total"": 3046}, ""2022""...","{""names"": [""Fredrick J Groshans"", ""Jill M Gros...",False,M-H,901000.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5493,"3720-Yakima-Ave,-Tacoma,-WA-98418","3720 Yakima Ave, Tacoma, WA 98418",3720 Yakima Ave,Unknown,Tacoma,WA,98418,Pierce,47.223865,-122.443705,...,2015-08-31T00:00:00.000Z,"""{\""architectureType\"": \""Single Story\"", \""ex...","{""2023"": {""year"": 2023, ""value"": 345600, ""land...","{""2023"": {""year"": 2023, ""total"": 3592}, ""2024""...","{""names"": [""Hoa H Bui"", ""Hong Son""], ""type"": ""...",True,RCX,117719.0,"{""2015-08-31"": {""event"": ""Sale"", ""date"": ""2015...",NaN
5494,"316-Hollyhock-Ln,-Hartland,-WI-53029","316 Hollyhock Ln, Hartland, WI 53029",316 Hollyhock Ln,Unknown,Hartland,WI,53029,Waukesha,43.124929,-88.341558,...,2019-08-05T00:00:00.000Z,"""{\""architectureType\"": \""Modern\"", \""exterior...","{""2022"": {""year"": 2022, ""value"": 586300, ""land...","{""2022"": {""year"": 2022, ""total"": 8401}}","{""names"": [""ERNESTO VILLARREAL"", ""ERNESTO VILL...",True,A,550000.0,NaN,NaN
5496,"1030-E-Lancaster-Ave,-Apt-819,-Bryn-Mawr,-PA-1...","1030 E Lancaster Ave, Apt 819, Bryn Mawr, PA 1...",1030 E Lancaster Ave,Apt 819,Bryn Mawr,PA,19010,Delaware,40.028230,-75.331276,...,2012-01-25T00:00:00.000Z,"""{\""architectureType\"": \""Condo / Apartment\"",...","{""2018"": {""year"": 2018, ""value"": 69650}, ""2019...","{""2018"": {""year"": 2018, ""total"": 2308}, ""2019""...","{""names"": [""CHRISTOPHER A DIPASQUA""], ""mailing...",False,Unknown,19800.0,"{""2012-01-25"": {""event"": ""Sale"", ""date"": ""2012...",NaN
5497,"4315-N-Browning-Dr,-West-Palm-Beach,-FL-33406","4315 N Browning Dr, West Palm Beach, FL 33406",4315 N Browning Dr,Unknown,West Palm Beach,FL,33406,Palm Beach,26.676598,-80.109007,...,1986-08-01T00:00:00.000Z,"""{\""cooling\"": true, \""coolingType\"": \""Commer...","{""2022"": {""year"": 2022, ""value"": 62377}}","{""2022"": {""year"": 2022, ""total"": 1017}}","{""names"": [""LOUISE E STUMP""], ""mailingAddress""...",True,RM,57000.0,NaN,NaN
5498,"13162-Dunwick-Rd,-Jacksonville,-FL-32256","13162 Dunwick Rd, Jacksonville, FL 32256",13162 Dunwick Rd,Unknown,Jacksonville,FL,32256,Duval,30.143313,-81.491554,...,2022-10-31T00:00:00.000Z,"""{\""cooling\"": true, \""coolingType\"": \""Centra...","{""2022"": {""year"": 2022, ""value"": 70000, ""land""...","{""2022"": {""year"": 2022, ""total"": 1192}, ""2023""...","{""names"": [""Phillip Michael Justice"", ""Ashlyn ...",True,PUD,542500.0,"{""2022-10-31"": {""event"": ""Sale"", ""date"": ""2022...",NaN

In [518]:
print(f"propertyrecords_df: {propertyrecords_df.columns}")

propertyrecords_df: Index(['id', 'formatted_address', 'address_line1', 'address_line2', 'city',
       'state', 'zip_code', 'county', 'latitude', 'longitude', 'property_type',
       'bedrooms', 'bathrooms', 'square_footage', 'lot_size', 'year_built',
       'assessor_id', 'legal_description', 'subdivision', 'last_sale_date',
       'features', 'tax_assessments', 'property_taxes', 'owner',
       'owner_occupied', 'zoning', 'last_sale_price', 'history', 'hoa_fees'],
      dtype='object')

## 8. Create Dimension Tables

In [519]:
# Create Location dimension:  (dimension table and merge with the index key)
location_dim = propertyrecords_df[['address_line1', 'city', 'state', 'zip_code', 'county', 'latitude', 'longitude', 'subdivision', 'zoning']].drop_duplicates().reset_index(drop = True)
location_dim['location_id'] = location_dim.index +1
location_dim['location_id'] = location_dim['location_id'].astype(int)
propertyrecords_df = propertyrecords_df.merge(location_dim[['location_id','address_line1', 'city', 'state', 'zip_code', 'county', 'latitude', 'longitude', 'subdivision', 'zoning']],
        on= ['address_line1', 'city', 'state', 'zip_code', 'county', 'latitude', 'longitude', 'subdivision', 'zoning'],
        how='left'
             )
print(f"location_dim: {location_dim.columns}" )
print(f"propertyrecords_df: {propertyrecords_df.columns}")

location_dim: Index(['address_line1', 'city', 'state', 'zip_code', 'county', 'latitude',
       'longitude', 'subdivision', 'zoning', 'location_id'],
      dtype='object')
propertyrecords_df: Index(['id', 'formatted_address', 'address_line1', 'address_line2', 'city',
       'state', 'zip_code', 'county', 'latitude', 'longitude', 'property_type',
       'bedrooms', 'bathrooms', 'square_footage', 'lot_size', 'year_built',
       'assessor_id', 'legal_description', 'subdivision', 'last_sale_date',
       'features', 'tax_assessments', 'property_taxes', 'owner',
       'owner_occupied', 'zoning', 'last_sale_price', 'history', 'hoa_fees',
       'location_id'],
      dtype='object')

In [520]:
# Create Features dimension: (dimension table and merge with the index key)
features_dim = propertyrecords_df[['features','property_type','zoning']].drop_duplicates().reset_index(drop = True)
features_dim['features_id'] = features_dim.index +1
features_dim['features_id'] =features_dim['features_id'].astype(int)
propertyrecords_df = propertyrecords_df.merge(features_dim[['features_id','features','property_type','zoning',]],
        on= ['features','property_type','zoning'],
        how='left' )
print(f"features_dim: {features_dim.columns}" ) 
print(f"propertyrecords_df: {propertyrecords_df.columns}")

features_dim: Index(['features', 'property_type', 'zoning', 'features_id'], dtype='object')
propertyrecords_df: Index(['id', 'formatted_address', 'address_line1', 'address_line2', 'city',
       'state', 'zip_code', 'county', 'latitude', 'longitude', 'property_type',
       'bedrooms', 'bathrooms', 'square_footage', 'lot_size', 'year_built',
       'assessor_id', 'legal_description', 'subdivision', 'last_sale_date',
       'features', 'tax_assessments', 'property_taxes', 'owner',
       'owner_occupied', 'zoning', 'last_sale_price', 'history', 'hoa_fees',
       'location_id', 'features_id'],
      dtype='object')

In [521]:
# Create Property dimension: (dimension table and merge with the index key)
property_dim = propertyrecords_df[['property_type', 'assessor_id', 'bedrooms', 'bathrooms', 'square_footage', 'legal_description', 'subdivision', 'features', 'zoning']].drop_duplicates().reset_index(drop = True)
property_dim['property_id'] = property_dim.index +1
property_dim[['property_id', 'bedrooms', 'bathrooms']] = property_dim[['property_id', 'bedrooms', 'bathrooms']].astype(int)
propertyrecords_df = propertyrecords_df.merge(property_dim[['property_id', 'property_type', 'assessor_id', 'bedrooms', 'bathrooms', 'square_footage', 'legal_description', 'subdivision', 'features', 'zoning']],
        on= ['property_type', 'assessor_id', 'bedrooms', 'bathrooms', 'square_footage', 'legal_description', 'subdivision', 'features', 'zoning'],
        how='left' )
print(f"property_dim: {property_dim.columns}" ) 
print(f"propertyrecords_df: {propertyrecords_df.columns}")

property_dim: Index(['property_type', 'assessor_id', 'bedrooms', 'bathrooms',
       'square_footage', 'legal_description', 'subdivision', 'features',
       'zoning', 'property_id'],
      dtype='object')
propertyrecords_df: Index(['id', 'formatted_address', 'address_line1', 'address_line2', 'city',
       'state', 'zip_code', 'county', 'latitude', 'longitude', 'property_type',
       'bedrooms', 'bathrooms', 'square_footage', 'lot_size', 'year_built',
       'assessor_id', 'legal_description', 'subdivision', 'last_sale_date',
       'features', 'tax_assessments', 'property_taxes', 'owner',
       'owner_occupied', 'zoning', 'last_sale_price', 'history', 'hoa_fees',
       'location_id', 'features_id', 'property_id'],
      dtype='object')

In [522]:
''' # Owner dimension

# Special cleaning for 'owner_dim'
owner_dim['owner_occupied'] = (
    owner_dim['owner_occupied']
    .map({'True': True, 'False': False})
    .astype('boolean')
)


owner_dim = propertyrecords_df[['owner', 'owner_occupied']].drop_duplicates().reset_index(drop = True)
owner_dim['owner_id'] = owner_dim.index +1
propertyrecords_df = propertyrecords_df.merge(owner_dim[['owner_id', 'owner', 'owner_occupied']],
        on= ['owner', 'owner_occupied'],
        how='left' )
print(f"owner_dim: {owner_dim.columns}" ) '''


# 🛠 1. Create owner_dim from propertyrecords_df
owner_dim = propertyrecords_df[['owner', 'owner_occupied']].drop_duplicates().reset_index(drop=True)

# 🧹 2. Clean the 'owner_occupied' field properly
owner_dim['owner_occupied'] = (
    owner_dim['owner_occupied']
    .map({'True': True, 'False': False})
    .astype('boolean')
)

# 🆔 3. Add owner_id
owner_dim['owner_id'] = owner_dim.index + 1
owner_dim['owner_id'] =owner_dim['owner_id'].astype(int)


# 🔗 4. Merge owner_id back into propertyrecords_df
propertyrecords_df = propertyrecords_df.merge(
    owner_dim[['owner_id', 'owner', 'owner_occupied']],
    on=['owner', 'owner_occupied'],
    how='left'
)
# 🔢 Ensure correct dtype
# propertyrecords_df['owner_id'] = propertyrecords_df['owner_id'].astype(int)

# 🖨 5. Confirm columns
print(f"owner_dim columns: {owner_dim.columns.tolist()}")

print(f"propertyrecords_df: {propertyrecords_df.columns}")

owner_dim columns: ['owner', 'owner_occupied', 'owner_id']
propertyrecords_df: Index(['id', 'formatted_address', 'address_line1', 'address_line2', 'city',
       'state', 'zip_code', 'county', 'latitude', 'longitude', 'property_type',
       'bedrooms', 'bathrooms', 'square_footage', 'lot_size', 'year_built',
       'assessor_id', 'legal_description', 'subdivision', 'last_sale_date',
       'features', 'tax_assessments', 'property_taxes', 'owner',
       'owner_occupied', 'zoning', 'last_sale_price', 'history', 'hoa_fees',
       'location_id', 'features_id', 'property_id', 'owner_id'],
      dtype='object')

In [523]:
# Tax dimension
# tax_dim = propertyrecords_df[['id', 'tax_annual', 'tax_exemptions', 'assessor_id']].copy()
# tax_dim.columns = ['property_id', 'annual_tax', 'tax_exemptions', 'assessor_id']
# tax_dim.to_csv('data/dimensions/tax_dim.csv', index=False)

In [524]:
# Propety taxes


'''
import pandas as pd

def generate_date_dim(start_date='1970-01-01', end_date='2030-12-31'):
    """
    Generate a full Date Dimension DataFrame from start_date to end_date.

    Args:
        start_date (str): The start date in 'YYYY-MM-DD' format.
        end_date (str): The end date in 'YYYY-MM-DD' format.

    Returns:
        pd.DataFrame: A date_dim DataFrame with all needed fields.
    """
    # Create daily date range
    dates = pd.date_range(start=start_date, end=end_date, freq='D')

    # Build date_dim
    date_dim = pd.DataFrame({
        'last_sale_date': dates,
        'year': dates.year,
        'month': dates.month,
        'day': dates.day,
        'quarter': dates.quarter,
        'day_name': dates.day_name(),
        'week': dates.isocalendar().week,
        'is_weekend': dates.weekday >= 5,  # Saturday(5), Sunday(6)
    })

    # Create a surrogate key
    date_dim['date_id'] = range(1, len(date_dim) + 1)

    return date_dim
'''

'''
import datetime as dt
from datetime import datetime, timedelta

# Fix month names in date_dim
if date_dim['month'].dtype == object:  # meaning it has text like 'October'
    month_name_to_number = {
        'January': 1, 'February': 2, 'March': 3, 'April': 4,
        'May': 5, 'June': 6, 'July': 7, 'August': 8,
        'September': 9, 'October': 10, 'November': 11, 'December': 12
    }
    date_dim['month'] = date_dim['month'].map(month_name_to_number)




propertyrecords_df['last_sale_date'] = pd.to_datetime(propertyrecords_df['last_sale_date'], errors='coerce', utc=True)

propertyrecords_df['year'] = propertyrecords_df['last_sale_date'].dt.year
propertyrecords_df['month'] = propertyrecords_df['last_sale_date'].dt.month_name()
propertyrecords_df['quarter'] = propertyrecords_df['last_sale_date'].dt.quarter
propertyrecords_df['day_name'] = propertyrecords_df['last_sale_date'].dt.day_name()

date_dim = propertyrecords_df[['day_name', 'month', 'quarter', 'year', 'last_sale_date']]
date_dim['date_id'] = date_dim.index +1

propertyrecords_df = propertyrecords_df.merge(date_dim[['date_id', 'day_name', 'month', 'quarter', 'year', 'last_sale_date']],
        on= ['day_name', 'month', 'quarter', 'year', 'last_sale_date'],
        how='left' )

print(f"date_dim: {date_dim.columns}" ) 
'''

'''

import datetime as dt
from datetime import datetime, timedelta

# -- Process 'last_sale_date'
propertyrecords_df['last_sale_date'] = pd.to_datetime(propertyrecords_df['last_sale_date'], errors='coerce', utc=True)

# -- Extract date components
propertyrecords_df['year'] = propertyrecords_df['last_sale_date'].dt.year
propertyrecords_df['month'] = propertyrecords_df['last_sale_date'].dt.month_name()  # Name like "October"
propertyrecords_df['quarter'] = propertyrecords_df['last_sale_date'].dt.quarter
propertyrecords_df['day_name'] = propertyrecords_df['last_sale_date'].dt.day_name()

# -- Create date_dim from propertyrecords_df
date_dim = propertyrecords_df[['day_name', 'month', 'quarter', 'year', 'last_sale_date']].drop_duplicates().reset_index(drop=True)
date_dim['date_id'] = date_dim.index + 1

# -- 🔥 NOW fix month names (after creating date_dim)
month_name_to_number = {
    'January': 1, 'February': 2, 'March': 3, 'April': 4,
    'May': 5, 'June': 6, 'July': 7, 'August': 8,
    'September': 9, 'October': 10, 'November': 11, 'December': 12
}
date_dim['month'] = date_dim['month'].map(month_name_to_number)

# -- Merge back date_id into propertyrecords_df
propertyrecords_df = propertyrecords_df.merge(
    date_dim[['date_id', 'day_name', 'month', 'quarter', 'year', 'last_sale_date']],
    on=['day_name', 'month', 'quarter', 'year', 'last_sale_date'],
    how='left'
)

print(f"date_dim: {date_dim.columns}")
'''
'''
import datetime as dt
from datetime import datetime, timedelta
# -- Create date_dim based ONLY on unique dates
all_dates = propertyrecords_df['last_sale_date'].dropna().drop_duplicates().sort_values()

date_dim = pd.DataFrame({
    'last_sale_date': all_dates
})

# -- Process 'last_sale_date'
all_dates['last_sale_date'] = pd.to_datetime(all_dates['last_sale_date'], errors='coerce', utc=True)

# -- Extract date components
all_dates['year'] = all_dates['last_sale_date'].dt.year
all_dates['month'] = all_dates['last_sale_date'].dt.month_name()
all_dates['quarter'] = all_dates['last_sale_date'].dt.quarter
all_dates['day_name'] = all_dates['last_sale_date'].dt.day_name()

# -- Create date_dim
date_dim = all_dates[['day_name', 'month', 'quarter', 'year', 'last_sale_date']].drop_duplicates().reset_index(drop=True)
date_dim['date_id'] = date_dim.index + 1

# -- Fix month names to numbers
month_name_to_number = {
    'January': 1, 'February': 2, 'March': 3, 'April': 4,
    'May': 5, 'June': 6, 'July': 7, 'August': 8,
    'September': 9, 'October': 10, 'November': 11, 'December': 12
}
date_dim['month'] = date_dim['month'].map(month_name_to_number)

# -- 🔥 IMPORTANT: fix month in propertyrecords_df too!
all_dates['month'] = all_dates['month'].map(month_name_to_number)

# -- Merge
propertyrecords_df = propertyrecords_df.merge(
    date_dim[['date_id', 'day_name', 'month', 'quarter', 'year', 'last_sale_date']],
    on=['day_name', 'month', 'quarter', 'year', 'last_sale_date'],
    how='left'
)

print(f"date_dim: {date_dim.columns}")

'''

'''
# -- Create date_dim based ONLY on unique dates
all_dates = propertyrecords_df['last_sale_date'].dropna().drop_duplicates().sort_values()

date_dim = pd.DataFrame({
    'last_sale_date': all_dates
})

# -- Extract components
date_dim['year'] = date_dim['last_sale_date'].dt.year
date_dim['month'] = date_dim['last_sale_date'].dt.month
date_dim['quarter'] = date_dim['last_sale_date'].dt.quarter
date_dim['day_name'] = date_dim['last_sale_date'].dt.day_name()

# -- Assign date_id based on the order
date_dim['date_id'] = date_dim.index + 1

# -- Now propertyrecords_df can map safely
propertyrecords_df = propertyrecords_df.merge(
    date_dim[['date_id', 'last_sale_date']],
    on='last_sale_date',
    how='left'
)

print(f"✅ date_dim created with {len(date_dim)} dates")

'''
'''

import datetime as dt
from datetime import datetime, timedelta
import pandas as pd

# -- Ensure 'last_sale_date' is datetime
propertyrecords_df['last_sale_date'] = pd.to_datetime(propertyrecords_df['last_sale_date'], errors='coerce', utc=True)

# -- Step 1: Create date_dim based on unique last_sale_date
all_dates = propertyrecords_df['last_sale_date'].dropna().drop_duplicates().sort_values().astype(int)

date_dim = pd.DataFrame({'last_sale_date': all_dates})

# -- Step 2: Extract date components
date_dim['year'] = date_dim['last_sale_date'].dt.year
date_dim['month'] = date_dim['last_sale_date'].dt.month  
date_dim['quarter'] = date_dim['last_sale_date'].dt.quarter
date_dim['day_name'] = date_dim['last_sale_date'].dt.day_name()

# -- Step 3: Assign date_id
date_dim = date_dim.reset_index(drop=True)
date_dim['date_id'] = date_dim.index + 1

# -- Step 4: Merge date_id back to propertyrecords_df
propertyrecords_df = propertyrecords_df.merge(
    date_dim[['date_id', 'last_sale_date']], 
    on='last_sale_date', 
    how='left'
)

print(f"✅ date_dim created with {len(date_dim)} rows: {list(date_dim.columns)}")

print(f"✅ propertyrecords_df columns after merge: {list(propertyrecords_df.columns)}")

'''


'''
import pandas as pd
import datetime as dt

# -- Step 1: Make sure last_sale_date is datetime
propertyrecords_df['last_sale_date'] = pd.to_datetime(propertyrecords_df['last_sale_date'], errors='coerce', utc=True)

# -- Step 2: Create date_dim from unique last_sale_dates
date_dim = (
    propertyrecords_df[['last_sale_date']]
    .dropna()
    .drop_duplicates()
    .sort_values('last_sale_date')
    .reset_index(drop=True)
)

# -- Step 3: Extract components
date_dim['year'] = date_dim['last_sale_date'].dt.year
date_dim['month'] = date_dim['last_sale_date'].dt.month  # numeric month# month as number (1-12)
date_dim['quarter'] = date_dim['last_sale_date'].dt.quarter
date_dim['day_name'] = date_dim['last_sale_date'].dt.day_name()

# -- Step 4: Add date_id (sequential)
date_dim['date_id'] = date_dim.index + 1

# -- Step 5: Merge date_id back into propertyrecords_df
propertyrecords_df = propertyrecords_df.merge(
    date_dim[['last_sale_date', 'date_id']],
    on='last_sale_date',
    how='left'
)

# -- Step 6: Done!
print(f"✅ date_dim created with {len(date_dim)} rows: {list(date_dim.columns)}"
      
print(f"✅ propertyrecords_df columns after merge: {list(propertyrecords_df.columns)}")

'''




'''
# -- Build date_dim
date_dim = (
    propertyrecords_df[['last_sale_date']]
    .dropna()
    .drop_duplicates()
    .sort_values('last_sale_date')
    .reset_index(drop=True)
)

date_dim['year'] = date_dim['last_sale_date'].dt.year
date_dim['month'] = date_dim['last_sale_date'].dt.month
date_dim['quarter'] = date_dim['last_sale_date'].dt.quarter
date_dim['day_name'] = date_dim['last_sale_date'].dt.day_name()
date_dim['date_id'] = date_dim.index + 1

# -- Merge
propertyrecords_df = propertyrecords_df.merge(
    date_dim[['last_sale_date', 'date_id']],
    on='last_sale_date',
    how='left'
)

# -- Check for missing date_id
missing_date_ids = propertyrecords_df[propertyrecords_df['date_id'].isna()]
print(f"❓ Missing date_ids: {len(missing_date_ids)} rows")

# -- Fix
if not missing_date_ids.empty:
    print("⚠️ Dropping rows with missing date_id")
    propertyrecords_df = propertyrecords_df.dropna(subset=['date_id'])

propertyrecords_df['date_id'] = propertyrecords_df['date_id'].astype(int)  # Safe to integer

# ✅ Now it's safe to insert!
'''


'''
# -- Build date_dim
date_dim = (
    propertyrecords_df[['last_sale_date']]
    .dropna()
    .drop_duplicates()
    .sort_values('last_sale_date')
    .reset_index(drop=True)
)

# 🛠️ Fix: force into datetime
date_dim['last_sale_date'] = pd.to_datetime(date_dim['last_sale_date'], errors='coerce', utc=True)

# -- Extract components
date_dim['year'] = date_dim['last_sale_date'].dt.year
date_dim['month'] = date_dim['last_sale_date'].dt.month
date_dim['quarter'] = date_dim['last_sale_date'].dt.quarter
date_dim['day_name'] = date_dim['last_sale_date'].dt.day_name()

# -- Create surrogate key
date_dim['date_id'] = date_dim.index + 1

# -- Merge
propertyrecords_df = propertyrecords_df.merge(
    date_dim[['last_sale_date', 'date_id']],
    on='last_sale_date',
    how='left'
)

# -- Check for missing date_id
missing_date_ids = propertyrecords_df[propertyrecords_df['date_id'].isna()]
print(f"❓ Missing date_ids: {len(missing_date_ids)} rows")

# -- Fix
if not missing_date_ids.empty:
    print("⚠️ Dropping rows with missing date_id")
    propertyrecords_df = propertyrecords_df.dropna(subset=['date_id'])

propertyrecords_df['date_id'] = propertyrecords_df['date_id'].astype(int)  # Safe to integer

# ✅ Now it's safe to insert!
'''
'''
# 1. Fix propertyrecords_df['last_sale_date']
propertyrecords_df['last_sale_date'] = pd.to_datetime(propertyrecords_df['last_sale_date'], errors='coerce', utc=True)

# 2. Build date_dim
date_dim = (
    propertyrecords_df[['last_sale_date']]
    .dropna()
    .drop_duplicates()
    .sort_values('last_sale_date')
    .reset_index(drop=True)
)
date_dim['year'] = date_dim['last_sale_date'].dt.year
date_dim['month'] = date_dim['last_sale_date'].dt.month
date_dim['quarter'] = date_dim['last_sale_date'].dt.quarter
date_dim['day_name'] = date_dim['last_sale_date'].dt.day_name()
date_dim['date_id'] = date_dim.index + 1

# 3. Merge
propertyrecords_df = propertyrecords_df.merge(
    date_dim[['last_sale_date', 'date_id']],
    on='last_sale_date',
    how='left'
)

# 4. Handle missing date_ids if any
missing_date_ids = propertyrecords_df[propertyrecords_df['date_id'].isna()]
print(f"❓ Missing date_ids: {len(missing_date_ids)} rows")

if not missing_date_ids.empty:
    print("⚠️ Dropping rows with missing date_id")
    propertyrecords_df = propertyrecords_df.dropna(subset=['date_id'])

propertyrecords_df['date_id'] = propertyrecords_df['date_id'].astype(int)
'''



print("Codes not needed")

Codes not needed

In [525]:
# Sale dimension
# sale_dim = propertyrecords_df[['id', 'last_sale_date', 'last_sale_price', 'price_per_sqft']].copy()
# sale_dim.columns = ['property_id', 'sale_date', 'sale_price', 'price_per_sqft']
# sale_dim.to_csv('data/dimensions/sale_dim.csv', index=False)

In [526]:
# Date dimension

# date_dim_generator.py



import pandas as pd

def generate_date_dim(start_date="1970-01-01", end_date="2030-12-31"):
    """
    Generates a full date dimension dataframe between start_date and end_date.

    Returns:
        pd.DataFrame: A complete date dimension table with a surrogate key (date_id).
    """
    # Generate full daily range with UTC
    date_range = pd.date_range(start=start_date, end=end_date, freq='D', tz='UTC')

    # Create the date_dim DataFrame
    date_dim = pd.DataFrame({'last_sale_date': date_range})

    # Extract components
    date_dim['year'] = date_dim['last_sale_date'].dt.year
    date_dim['month'] = date_dim['last_sale_date'].dt.month
    date_dim['day'] = date_dim['last_sale_date'].dt.day
    date_dim['quarter'] = date_dim['last_sale_date'].dt.quarter
    date_dim['day_name'] = date_dim['last_sale_date'].dt.day_name()
    date_dim['month_name'] = date_dim['last_sale_date'].dt.month_name()
    date_dim['week_of_year'] = date_dim['last_sale_date'].dt.isocalendar().week
    date_dim['is_weekend'] = date_dim['day_name'].isin(['Saturday', 'Sunday']).astype(int)

    # Smart surrogate key: YYYYMMDD
    date_dim['date_id'] = (
        date_dim['year'] * 10000 +
        date_dim['month'] * 100 +
        date_dim['day']
    )
    date_dim['date_id'] =date_dim['date_id'].astype(int)
    
    # Final column order
    date_dim = date_dim[[
        'date_id', 'last_sale_date', 'year', 'month', 'day',
        'quarter', 'day_name', 'month_name', 'week_of_year', 'is_weekend'
    ]]

    return date_dim


# 🧠 Generate and preview the date_dim
date_dim = generate_date_dim()
print(date_dim.head())
print(date_dim.tail())

# ✅ Prepare propertyrecords_df for merge
propertyrecords_df['last_sale_date'] = pd.to_datetime(
    propertyrecords_df['last_sale_date'], errors='coerce', utc=True
)

# 🔗 Merge date_id from date_dim
propertyrecords_df = propertyrecords_df.merge(
    date_dim[['last_sale_date', 'date_id']],
    on='last_sale_date',
    how='left'
)

# 🧹 Drop records with missing date_id (if any)
missing_count = propertyrecords_df['date_id'].isna().sum()
if missing_count > 0:
    print(f"⚠️ {missing_count} records have missing date_id and will be dropped.")
    propertyrecords_df = propertyrecords_df.dropna(subset=['date_id'])

# 🔢 Ensure correct dtype
propertyrecords_df['date_id'] = propertyrecords_df['date_id'].astype(int)

# ✅ Final checks
print(propertyrecords_df.head())
print(f"propertyrecords_df columns: {list(propertyrecords_df.columns)}")
print(date_dim.columns)

    date_id            last_sale_date  year  month  day  quarter  day_name  \
0  19700101 1970-01-01 00:00:00+00:00  1970      1    1        1  Thursday
1  19700102 1970-01-02 00:00:00+00:00  1970      1    2        1    Friday
2  19700103 1970-01-03 00:00:00+00:00  1970      1    3        1  Saturday
3  19700104 1970-01-04 00:00:00+00:00  1970      1    4        1    Sunday
4  19700105 1970-01-05 00:00:00+00:00  1970      1    5        1    Monday

  month_name  week_of_year  is_weekend
0    January             1           0
1    January             1           0
2    January             1           1
3    January             1           1
4    January             2           0
        date_id            last_sale_date  year  month  day  quarter  \
22275  20301227 2030-12-27 00:00:00+00:00  2030     12   27        4
22276  20301228 2030-12-28 00:00:00+00:00  2030     12   28        4
22277  20301229 2030-12-29 00:00:00+00:00  2030     12   29        4
22278  20301230 2030-12-30 00:00:00+00:00  2030     12   30        4
22279  20301231 2030-12-31 00:00:00+00:00  2030     12   31        4

       day_name month_name  week_of_year  is_weekend
22275    Friday   December            52           0
22276  Saturday   December            52           1
22277    Sunday   December            52           1
22278    Monday   December             1           0
22279   Tuesday   December             1           0
⚠️ 4 records have missing date_id and will be dropped.
                                                  id  \
0        801-Plate-St,-Unit-206,-Rochester,-MI-48307
1       11328-Van-Buren-St-NE,-Minneapolis,-MN-55434
2       1148-S-Ventura-Cir,-Unit-H,-Aurora,-CO-80017
3  135-Bordentown-Crosswicks-Rd,-Crosswicks,-NJ-0...
4  7700-E-Princess-Dr,-Unit-17,-Scottsdale,-AZ-85255

                                   formatted_address  \
0        801 Plate St, Unit 206, Rochester, MI 48307
1       11328 Van Buren St NE, Minneapolis, MN 55434
2       1148 S Ventura Cir, Unit H, Aurora, CO 80017
3  135 Bordentown Crosswicks Rd, Crosswicks, NJ 0...
4  7700 E Princess Dr, Unit 17, Scottsdale, AZ 85255

                  address_line1 address_line2         city state zip_code  \
0                  801 Plate St      Unit 206    Rochester    MI    48307
1         11328 Van Buren St NE       Unknown  Minneapolis    MN    55434
2            1148 S Ventura Cir        Unit H       Aurora    CO    80017
3  135 Bordentown Crosswicks Rd       Unknown   Crosswicks    NJ    08515
4            7700 E Princess Dr       Unit 17   Scottsdale    AZ    85255

       county   latitude   longitude  ... owner_occupied   zoning  \
0     Oakland  42.687461  -83.125512  ...          False       KI
1       Anoka  45.176130  -93.250083  ...           True  Unknown
2    Arapahoe  39.695339 -104.776629  ...           True      PUD
3  Burlington  40.144733  -74.663560  ...           True     PVD2
4    Maricopa  33.645192 -111.913378  ...          False      M-H

   last_sale_price                                            history  \
0         119222.0  {"2023-10-10": {"event": "Sale", "date": "2023...
1         239900.0  {"2015-05-19": {"event": "Sale", "date": "2015...
2         308000.0  {"2023-05-17": {"event": "Sale", "date": "2023...
3          57810.0                                                NaN
4         901000.0                                                NaN

   hoa_fees  location_id features_id property_id owner_id   date_id
0       NaN            1           1         1.0      NaN  20231010
1       NaN            2           2         2.0      NaN  20150519
2       NaN            3           3         3.0      NaN  20230517
3       NaN            4           4         4.0      NaN  20090819
4       NaN            5           5         5.0      NaN  20220401

[5 rows x 34 columns]
propertyrecords_df columns: ['id', 'formatted_address', 'address_line1', 'address_line2', 'city', 'state', 'zip_code', 'county', 'latitude', 'longitude', 'property_type', 'bedrooms', 'bathrooms', 'square_footage', 'lot_size', 'year_built', 'assessor_id', 'legal_description', 'subdivision', 'last_sale_date', 'features', 'tax_assessments', 'property_taxes', 'owner', 'owner_occupied', 'zoning', 'last_sale_price', 'history', 'hoa_fees', 'location_id', 'features_id', 'property_id', 'owner_id', 'date_id']
Index(['date_id', 'last_sale_date', 'year', 'month', 'day', 'quarter',
       'day_name', 'month_name', 'week_of_year', 'is_weekend'],
      dtype='object')

## 9. Create Fact Table

In [527]:
fact_table_columns = ['location_id', 'features_id', 'property_id', 'owner_id', 'date_id', 'last_sale_price', 'property_taxes', 'tax_assessments']

missing_cols = [col for col in fact_table_columns if col not in propertyrecords_df.columns]
assert not missing_cols, f"❌ Missing columns in propertyrecords_df: {missing_cols}"

In [528]:
def fact_tables():
    '''
    fact_table_columns = ['location_id', 'features_id', 'property_id', 'owner_id', 'date_id', 'last_sale_price', 'property_taxes', 'tax_assessments']
    fact_table = propertyrecords_df[fact_table_columns]
    '''
    try:
        fact_table = propertyrecords_df[['last_sale_price', 'property_taxes', 'tax_assessments']].copy()

        # Add dimension keys
        fact_table['location_id'] = propertyrecords_df.index + 1
        fact_table['features_id'] = propertyrecords_df.index + 1
        fact_table['property_id'] = propertyrecords_df.index + 1
        fact_table['owner_id'] = propertyrecords_df.index + 1
        fact_table['date_id'] = propertyrecords_df.index + 1

    except KeyError as e:
        logger.error(f"Missing required column: {str(e)}")
        raise
    fact_table.head()

    print(f"propertyrecords_df: {propertyrecords_df.columns}")
    
fact_tables()

propertyrecords_df: Index(['id', 'formatted_address', 'address_line1', 'address_line2', 'city',
       'state', 'zip_code', 'county', 'latitude', 'longitude', 'property_type',
       'bedrooms', 'bathrooms', 'square_footage', 'lot_size', 'year_built',
       'assessor_id', 'legal_description', 'subdivision', 'last_sale_date',
       'features', 'tax_assessments', 'property_taxes', 'owner',
       'owner_occupied', 'zoning', 'last_sale_price', 'history', 'hoa_fees',
       'location_id', 'features_id', 'property_id', 'owner_id', 'date_id'],
      dtype='object')

In [529]:
print(f"fact_table: {fact_table.columns}")

fact_table: Index(['last_sale_price', 'property_taxes', 'tax_assessments', 'location_id',
       'features_id', 'property_id', 'owner_id', 'date_id'],
      dtype='object')

In [530]:
'''
Main df
propertyrecords_df: Index(['id', 'formatted_address', 'address_line1', 'address_line2', 'city',
       'state', 'zip_code', 'county', 'latitude', 'longitude', 'property_type',
       'bedrooms', 'bathrooms', 'square_footage', 'lot_size', 'year_built',
       'assessor_id', 'legal_description', 'subdivision', 'last_sale_date',
       'features', 'tax_assessments', 'property_taxes', 'owner',
       'owner_occupied', 'zoning', 'last_sale_price', 'history', 'hoa_fees',
       'location_id', 'features_id', 'property_id', 'owner_id', 'year',
       'month', 'quarter', 'day_name', 'date_id'],
      dtype='object')

Dimensions Tables
location_dim: Index(['address_line1', 'city', 'state', 'zip_code', 'county', 'latitude',
       'longitude', 'subdivision', 'zoning', 'location_id'],
      dtype='object')
features_dim: Index(['features', 'property_type', 'zoning', 'features_id'], dtype='object')
property_dim: Index(['property_type', 'assessor_id', 'bedrooms', 'bathrooms',
       'square_footage', 'legal_description', 'subdivision', 'features',
       'zoning', 'property_id'],
      dtype='object')
owner_dim: Index(['owner', 'owner_occupied', 'owner_id'], dtype='object')
date_dim: Index(['day_name', 'month', 'quarter', 'year', 'last_sale_date', 'date_id'], dtype='object')

Fact Table
fact_table: Index(['location_id', 'features_id', 'property_id', 'owner_id', 'date_id',
       'last_sale_price', 'property_taxes', 'tax_assessments'],
      dtype='object')
'''
print('Nothing')

Nothing

## 10. Create csv files for Dimension Tables and Fact table

In [531]:
# 
def create_tables():
    propertyrecords_df.to_csv('data/processed/property_records.csv', index=False)

    fact_table.to_csv('data/facts/fact_table.csv', index=False)

    location_dim.to_csv('data/dimensions/location_dim.csv', index=False)
    features_dim.to_csv('data/dimensions/features_dim.csv', index=False)
    property_dim.to_csv('data/dimensions/property_dim.csv', index=False)
    owner_dim.to_csv('data/dimensions/owner_dim.csv', index=False)
    date_dim.to_csv('data/dimensions/date_dim.csv', index=False)
    
    print("tables are now created")
create_tables()

tables are now created

In [532]:
# propertyrecords_df.columns

print(fact_table.shape)
print(fact_table.head())

(2796, 8)
   last_sale_price                                     property_taxes  \
0         119222.0            {"2021": {"year": 2021, "total": 1013}}
1         239900.0  {"2019": {"year": 2019, "total": 2668}, "2023"...
2         308000.0  {"2019": {"year": 2019, "total": 1315}, "2021"...
3          57810.0            {"2021": {"year": 2021, "total": 1787}}
4         901000.0  {"2021": {"year": 2021, "total": 3046}, "2022"...

                                     tax_assessments  location_id  \
0           {"2023": {"year": 2023, "value": 43210}}            1
1  {"2019": {"year": 2019, "value": 254200, "land...            2
2  {"2019": {"year": 2019, "value": 12699}, "2020...            3
3  {"2022": {"year": 2022, "value": 57800, "land"...            4
4  {"2022": {"year": 2022, "value": 44630, "land"...            5

   features_id  property_id  owner_id  date_id
0            1            1         1        1
1            2            2         2        2
2            3            3         3        3
3            4            4         4        4
4            5            5         5        5

## 12. PostgreSQL Setup and Data Loading

In [533]:
import psycopg2

# Admin connection settings
DB_NAME = "postgres"  # connect to default 'postgres' db
DB_USER = "postgres"
DB_PASSWORD = "Soji1234"
DB_HOST = "localhost"
DB_PORT = "5432"

def create_admin_connection():
    """Connect as an admin to PostgreSQL"""
    try:
        conn = psycopg2.connect(
            dbname=DB_NAME,
            user=DB_USER,
            password=DB_PASSWORD,
            host=DB_HOST,
            port=DB_PORT
        )
        conn.autocommit = True  # <-- IMPORTANT!!
        print("✅ Successfully connected to admin PostgreSQL (postgres)")
        return conn
    except Exception as e:
        print(f"❌ Error connecting to PostgreSQL: {e}")
        return None

def create_db_and_user():
    conn = create_admin_connection()
    cursor = conn.cursor()

    try:
        # 1. Create user if not exists
        cursor.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'etl_user') THEN
                CREATE ROLE etl_user LOGIN PASSWORD 'pipeline';
            END IF;
        END
        $$;
        """)
        print("✅ User 'etl_user' created (or already exists).")

        # 2. Create database separately (no transaction block!)
        cursor.execute("SELECT 1 FROM pg_database WHERE datname = 'etl_pipeline_db';")
        exists = cursor.fetchone()
        if not exists:
            cursor.execute("CREATE DATABASE etl_pipeline_db;")
            print("✅ Database 'etl_pipeline_db' created.")
        else:
            print("✅ Database 'etl_pipeline_db' already exists.")

    except Exception as e:
        print(f"❌ Error during setup: {e}")

    finally:
        cursor.close()
        conn.close()

create_db_and_user()

✅ Successfully connected to admin PostgreSQL (postgres)
✅ User 'etl_user' created (or already exists).
✅ Database 'etl_pipeline_db' already exists.

In [534]:
# Connect to admin
# conn = create_admin_connection()
# cursor = conn.cursor()


def setup_database():
    """Creates a fresh user and database for the ETL pipeline."""
    conn = create_admin_connection()
    conn.autocommit = True  # Needed to run CREATE DATABASE
    cursor = conn.cursor()

    try:
        
    
        # Step 1: Disconnect all other sessions
        cursor.execute("""
            SELECT pg_terminate_backend(pid)
            FROM pg_stat_activity
            WHERE datname = 'etl_pipeline_db'
            AND pid <> pg_backend_pid();
        """)
        print("🔌 Disconnected all active connections to 'etl_pipeline_db'.")

        # Step 1: Drop user and database if they already exist
        cursor.execute("DROP DATABASE IF EXISTS etl_pipeline_db;")
        print("🧹 Old database 'etl_pipeline_db' dropped.")
        
        cursor.execute("DROP USER IF EXISTS etl_user;")
        print("🧹 Old user 'etl_user' dropped.")

        # Step 2: Create user
        cursor.execute("CREATE USER etl_user WITH PASSWORD 'pipeline';")
        print("✅ User 'etl_user' created.")

        # Step 3: Create database
        cursor.execute("CREATE DATABASE etl_pipeline_db OWNER etl_user;")
        print("✅ Database 'etl_pipeline_db' created.")

        # Step 4: Grant privileges
        # Not needed separately because OWNER gets all privileges
        # cursor.execute("GRANT ALL PRIVILEGES ON DATABASE etl_pipeline_db TO etl_user;")
        print("✅ 'etl_user' automatically owns 'etl_pipeline_db'.")

    except Exception as e:
        print(f"❌ Error during setup: {e}")
        raise

    finally:
        cursor.close()
        conn.close()
        print("🔒 Admin connection closed.")

#if __name__ == "__main__":
setup_database()

✅ Successfully connected to admin PostgreSQL (postgres)
🔌 Disconnected all active connections to 'etl_pipeline_db'.
🧹 Old database 'etl_pipeline_db' dropped.
🧹 Old user 'etl_user' dropped.
✅ User 'etl_user' created.
✅ Database 'etl_pipeline_db' created.
✅ 'etl_user' automatically owns 'etl_pipeline_db'.
🔒 Admin connection closed.

In [535]:
# Now connect to the new database as etl_user
def get_connection():
    try:
        conn = psycopg2.connect(
            dbname="etl_pipeline_db",   # new database
            user="etl_user",
            password="pipeline",
            host="localhost",
            port=5432
        )
        print("✅ Connected to 'etl_pipeline_db' as etl_user ")
        return conn
    except Exception as e:
        print(f"❌ Error connecting to new db: {e}")
        return None

conn = get_connection()
cursor = conn.cursor()
print("✅  function called get_connection is defined")

✅ Connected to 'etl_pipeline_db' as etl_user
✅  function called get_connection is defined

In [536]:
schema_statements = [
        # location_dim
        """
        CREATE TABLE IF NOT EXISTS etl_pipeline_db.location_dim (
            location_id SERIAL PRIMARY KEY,
            address_line1 TEXT,
            city TEXT,
            state TEXT,
            zip_code TEXT,
            county TEXT,
            latitude FLOAT,
            longitude FLOAT,
            subdivision TEXT,
            zoning TEXT
        );
        """,

        # features_dim
        """
        CREATE TABLE IF NOT EXISTS etl_pipeline_db.features_dim (
            features_id SERIAL PRIMARY KEY,
            features TEXT,
            property_type TEXT,
            zoning TEXT
        );
        """,

        # property_dim
        """
        CREATE TABLE IF NOT EXISTS etl_pipeline_db.property_dim (
            property_id SERIAL PRIMARY KEY,
            property_type TEXT,
            assessor_id TEXT,
            bedrooms INTEGER,
            bathrooms INTEGER,
            square_footage FLOAT,
            legal_description TEXT,
            subdivision TEXT,
            features TEXT,
            zoning TEXT
        );
        """,

        # owner_dim
        """
        CREATE TABLE IF NOT EXISTS etl_pipeline_db.owner_dim (
            owner_id SERIAL PRIMARY KEY,
            owner TEXT,
            owner_occupied BOOLEAN
        );
        """,

        # date_dim
        """
        CREATE TABLE IF NOT EXISTS etl_pipeline_db.date_dim (
            date_id INTEGER PRIMARY KEY,
            year INTEGER,
            month INTEGER,
            day INTEGER,
            quarter INTEGER,
            day_name TEXT,
            month_name TEXT,
            week_of_year INTEGER,
            is_weekend INTEGER,
            last_sale_date TIMESTAMP WITH TIME ZONE
        );
        """,

        # fact_table
        """
        CREATE TABLE IF NOT EXISTS etl_pipeline_db.fact_table (
            fact_id SERIAL PRIMARY KEY,
            location_id INT REFERENCES etl_pipeline_db.location_dim(location_id),
            features_id INT REFERENCES etl_pipeline_db.features_dim(features_id),
            property_id INT REFERENCES etl_pipeline_db.property_dim(property_id),
            owner_id INT REFERENCES etl_pipeline_db.owner_dim(owner_id),
            date_id INT REFERENCES etl_pipeline_db.date_dim(date_id),
            last_sale_price DOUBLE PRECISION,
            property_taxes DOUBLE PRECISION,
            tax_assessments DOUBLE PRECISION
        );
        """
    ]

print(" schema_statements is defined as a list")

 schema_statements is defined as a list

In [537]:
# create_tables.py

import psycopg2

conn = get_connection()
def create_tables():
    """Connects to PostgreSQL and creates all required tables in the etl_pipeline_db schema."""
    try:
        cursor = conn.cursor()

        # Ensure schema exists
        cursor.execute("CREATE SCHEMA IF NOT EXISTS etl_pipeline_db;")

        # Create dimension and fact tables
        for stmt in schema_statements:
            cursor.execute(stmt)

        conn.commit()
        print("✅ All tables created successfully in 'etl_pipeline_db' schema.")

    except Exception as e:
        print("❌ Error creating tables:", e)

    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()
        print("🔒 PostgreSQL connection closed.")

create_tables()
    
print("✅ PostgreSQL schema and tables created or verified.")

✅ Connected to 'etl_pipeline_db' as etl_user
✅ All tables created successfully in 'etl_pipeline_db' schema.
🔒 PostgreSQL connection closed.
✅ PostgreSQL schema and tables created or verified.

In [538]:
def load_data_from_csv_to_table(csv_path, table_name):
    conn = get_connection()
    cursor = conn.cursor()

    with open(csv_path, 'r', encoding='utf-8') as file:
        reader = csv.reader(file)
        headers = next(reader)  # Extract header row
        columns = ', '.join(headers)

        for row in reader:
            # Convert "Unknown", "Not Available", or empty strings to None
            cleaned_row = [None if val in ("", "Unknown", "Not Available") else val for val in row]

            placeholders = ', '.join(['%s'] * len(cleaned_row))
            query = f'INSERT INTO {table_name} ({columns}) VALUES ({placeholders});'
            cursor.execute(query, cleaned_row)

    conn.commit()
    cursor.close()
    conn.close()
    print("✅ The function 'load_data_from_csv_to_table' was called")
    
print("✅ The function 'load_data_from_csv_to_table' is created to load fact and dimension csv to postgreSQL")

✅ The function 'load_data_from_csv_to_table' is created to load fact and dimension csv to postgreSQL

In [539]:
import csv
# CSV file paths
property_records_csv = "data/processed/property_records.csv"

location_dim_csv = "data/dimensions/location_dim.csv"
features_dim_csv = "data/dimensions/features_dim.csv"
property_dim_csv = "data/dimensions/property_dim.csv"
owner_dim_csv = "data/dimensions/owner_dim.csv"
date_dim_csv = "data/dimensions/date_dim.csv"
fact_table_csv = "data/facts/fact_table.csv"

# PostgreSQL dimension tables and fact table
location_sql = "etl_pipeline_db.location_dim"
features_sql = "etl_pipeline_db.features_dim"
property_sql = "etl_pipeline_db.property_dim"
owner_sql = "etl_pipeline_db.owner_dim"
date_sql = "etl_pipeline_db.date_dim"
fact_table_sql = "etl_pipeline_db.fact_table"

In [540]:
load_data_from_csv_to_table(location_dim_csv, location_sql)
print("location_dim was loaded to 'location_sql' in postgreSQL")

✅ Connected to 'etl_pipeline_db' as etl_user
✅ The function 'load_data_from_csv_to_table' was called
location_dim was loaded to 'location_sql' in postgreSQL

In [541]:
load_data_from_csv_to_table(features_dim_csv, features_sql)
print("location_dim was loaded to 'features_sql' in postgreSQL")

✅ Connected to 'etl_pipeline_db' as etl_user
✅ The function 'load_data_from_csv_to_table' was called
location_dim was loaded to 'features_sql' in postgreSQL

In [542]:
load_data_from_csv_to_table(property_dim_csv, property_sql)
print("location_dim was loaded to 'property_sql' in postgreSQL")

✅ Connected to 'etl_pipeline_db' as etl_user
✅ The function 'load_data_from_csv_to_table' was called
location_dim was loaded to 'property_sql' in postgreSQL

In [543]:
load_data_from_csv_to_table(owner_dim_csv, owner_sql)
print("location_dim was loaded to 'owner_sql' in postgreSQL")

✅ Connected to 'etl_pipeline_db' as etl_user
✅ The function 'load_data_from_csv_to_table' was called
location_dim was loaded to 'owner_sql' in postgreSQL

In [544]:
load_data_from_csv_to_table(date_dim_csv, date_sql)
print("location_dim was loaded to 'date_sql' in postgreSQL")

✅ Connected to 'etl_pipeline_db' as etl_user
✅ The function 'load_data_from_csv_to_table' was called
location_dim was loaded to 'date_sql' in postgreSQL

In [545]:
# etl/load_fact.py


def load_fact_from_csv_to_table(csv_path, table_name, db_url="postgresql://etl_user:pipeline@localhost/etl_pipeline_db"):
    import pandas as pd
    from sqlalchemy import create_engine

    # Read the CSV
    df = pd.read_csv(csv_path)
    df.replace(["Unknown", "Not Available", "", "nan", "none"], pd.NA, inplace=True)

    # Use 'public' schema unless you created another one manually
    engine = create_engine(db_url)

    # Split schema.table correctly or default to public
    if '.' in table_name:
        schema, table = table_name.split('.')
    else:
        schema = 'public'
        table = table_name

    df.to_sql(
        name=table,
        con=engine,
        schema=schema,
        if_exists='replace',
        index=False
    )

    print(f"✅ Data loaded into {schema}.{table}")

    
import csv
import pandas as pd
import psycopg2
from psycopg2 import sql, extras


def load_fact_from_csv_to_table03(csv_path, table_name):
    """
    Efficiently loads a CSV file into a PostgreSQL table using psycopg2's execute_values.

    Args:
        csv_path (str): Path to the CSV file.
        table_name (str): Name of the target table, optionally including schema (e.g., 'public.fact_table')
    """
    # Read and clean CSV
    df = pd.read_csv(csv_path)
    df.replace(["Unknown", "Not Available", "", "nan", "none"], pd.NA, inplace=True)

    # Convert NaN to None for psycopg2
    records = df.where(pd.notnull(df), None).values.tolist()
    columns = list(df.columns)

    conn = get_connection()
    cursor = conn.cursor()

    try:
        # Build SQL dynamically
        cols = sql.SQL(', ').join(map(sql.Identifier, columns))
        insert_query = sql.SQL("INSERT INTO {} ({}) VALUES %s").format(
            sql.Identifier(*table_name.split('.')) if '.' not in table_name else sql.SQL('.').join(map(sql.Identifier, table_name.split('.'))),
            cols
        )

        # Efficient bulk insert
        extras.execute_values(cursor, insert_query, records)

        conn.commit()
        print(f"✅ Loaded {len(records)} rows into {table_name}")
    except Exception as e:
        conn.rollback()
        print(f"⛔ Failed to load data into {table_name}: {e}")
    finally:
        cursor.close()
        conn.close()

        
        
        
def load_fact_from_csv_to_table02(csv_path, table_name):
    conn = get_connection()
    cursor = conn.cursor()

    with open(csv_path, 'r', encoding='utf-8') as file:
        reader = csv.reader(file)
        headers = next(reader)  # Extract header row
        columns = ', '.join(headers)

        for row in reader:
            # Convert "Unknown", "Not Available", or empty strings to None
            cleaned_row = [None if val in ("", "Unknown", "Not Available") else val for val in row]

            placeholders = ', '.join(['%s'] * len(cleaned_row))
            query = f'INSERT INTO {table_name} ({columns}) VALUES ({placeholders});'
            cursor.execute(query, cleaned_row)

    conn.commit()
    cursor.close()
    conn.close()
    print("✅ The function 'load_fact_from_csv_to_table' was called")
    
print("✅ The function 'load_fact_from_csv_to_table' is created to load fact csv to postgreSQL")




    

print("✅ The function 'load_fact_from_csv_to_table' is created to load fact csv to postgreSQL")

✅ The function 'load_fact_from_csv_to_table' is created to load fact csv to postgreSQL
✅ The function 'load_fact_from_csv_to_table' is created to load fact csv to postgreSQL

In [546]:
load_fact_from_csv_to_table(fact_table_csv, fact_table_sql)
print("location_dim was loaded to 'fact_table_sql' in postgreSQL")

✅ Data loaded into etl_pipeline_db.fact_table
location_dim was loaded to 'fact_table_sql' in postgreSQL

In [547]:
import numpy as np
import psycopg2
from psycopg2 import sql
from datetime import datetime

def validate_data_types(df, table_name, conn, schema="etl_pipeline"):
    """Validate DataFrame columns against database schema"""
    cursor = conn.cursor()
    try:
        cursor.execute(f"""
            SELECT column_name, data_type 
            FROM information_schema.columns 
            WHERE table_schema = '{schema}' 
            AND table_name = '{table_name}'
        """)
        schema_types = {row[0]: row[1] for row in cursor.fetchall()}
        
        type_mapping = {
            'integer': 'int64',
            'bigint': 'int64',
            'smallint': 'int64',
            'numeric': 'float64',
            'real': 'float64',
            'double precision': 'float64',
            'text': 'object',
            'varchar': 'object',
            'date': 'datetime64[ns]',
            'timestamp': 'datetime64[ns]'
        }
        
        for col in df.columns:
            if col not in schema_types:
                raise ValueError(f"Column '{col}' not found in {schema}.{table_name}")
            
            expected_type = type_mapping.get(schema_types[col], 'object')
            if not np.issubdtype(df[col].dtype, np.dtype(expected_type)):
                try:
                    if 'int' in schema_types[col]:
                        df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')
                    elif 'numeric' in schema_types[col] or 'real' in schema_types[col]:
                        df[col] = pd.to_numeric(df[col], errors='coerce')
                    elif 'date' in schema_types[col] or 'timestamp' in schema_types[col]:
                        df[col] = pd.to_datetime(df[col], errors='coerce')
                except Exception as e:
                    raise ValueError(f"Failed to convert column '{col}' to {schema_types[col]}: {str(e)}")
        
        return df.replace({np.nan: None, 'NaN': None, '': None})

    finally:
        cursor.close()

def insert_dataframe(df, table_name, conn, schema="etl_pipeline", pk_column=None, batch_size=1000):
    """Enhanced version with data validation"""
    if df.empty:
        print(f"ℹ️ Empty DataFrame for {schema}.{table_name} - skipping")
        return 0

    try:
        # Validate and clean data
        df = validate_data_types(df, table_name, conn, schema)
        records = [tuple(x) for x in df.to_numpy()]
        
        cursor = conn.cursor()
        inserted_rows = 0
        
        # Build the INSERT query
        query = sql.SQL("""
            INSERT INTO {schema_table} ({columns})
            VALUES ({values})
            {conflict_clause}
        """).format(
            schema_table=sql.Identifier(schema, table_name),
            columns=sql.SQL(', ').join(map(sql.Identifier, df.columns)),
            values=sql.SQL(', ').join([sql.Placeholder()] * len(df.columns)),
            conflict_clause=sql.SQL("ON CONFLICT DO NOTHING") if pk_column else sql.SQL("")
        )

        # Execute in batches
        for i in range(0, len(records), batch_size):
            batch = records[i:i + batch_size]
            cursor.executemany(query, batch)
            inserted_rows += cursor.rowcount
            print(f"✓ Batch inserted {cursor.rowcount} rows to {schema}.{table_name}")

        conn.commit()
        print(f"✅ Total {inserted_rows} rows inserted to {schema}.{table_name}")
        return inserted_rows

    except Exception as e:
        conn.rollback()
        error_msg = f"❌ Error in {schema}.{table_name}: {str(e)}"
        print(error_msg)
        raise

    finally:
        if 'cursor' in locals() and cursor:
            cursor.close()

# Updated Configuration with Data Type Handling
TABLES_CONFIG = {
    'dimensions': {
        'location_dim': (location_dim, 'location_id'),
        'features_dim': (features_dim, 'feature_id'),
        'property_dim': (property_dim, 'property_id'),
        'owner_dim': (owner_dim, 'owner_id'),
        'date_dim': (date_dim.replace({'month': {'January': 1, 'February': 2, 'March': 3, 
                                               'April': 4, 'May': 5, 'June': 6,
                                               'July': 7, 'August': 8, 'September': 9,
                                               'October': 10, 'November': 11, 'December': 12}}), 
                     'date_id')
    },
    'fact': {
        'df': fact_table
    }
}

# Execute the pipeline
if __name__ == "__main__":
    try:
        run_etl_pipeline(TABLES_CONFIG)
        print("🎉 ETL Pipeline completed successfully!")
    except Exception as e:
        print(f"💥 ETL Pipeline failed: {str(e)}")
        exit(1)

💥 ETL Pipeline failed: name 'run_etl_pipeline' is not defined

In [558]:
import numpy as np
import psycopg2
from psycopg2 import sql

def insert_dataframe(df, table_name, conn, schema="etl_pipeline_db", pk_column=None, batch_size=1000):
    """
    Robust DataFrame insertion with:
    - Automatic NaN/NULL handling
    - Batch processing
    - Dynamic primary key handling
    - Comprehensive error reporting
    """
    if df.empty:
        print(f"ℹ️ Empty DataFrame for {schema}.{table_name} - skipping")
        return 0

    # Clean data and prepare for insertion
    df_clean = df.replace({np.nan: None, 'NaN': None, '': None})
    records = [tuple(x) for x in df_clean.to_numpy()]
    columns = list(df_clean.columns)
    
    cursor = conn.cursor()
    inserted_rows = 0
    
    try:
        # Build the base INSERT query
        query = sql.SQL("""
            INSERT INTO {schema_table} ({columns})
            VALUES ({values})
            {conflict_clause}
        """).format(
            schema_table=sql.Identifier(schema, table_name),
            columns=sql.SQL(', ').join(map(sql.Identifier, columns)),
            values=sql.SQL(', ').join([sql.Placeholder()] * len(columns)),
            conflict_clause=sql.SQL("ON CONFLICT DO NOTHING") if pk_column else sql.SQL("")
        )

        # Execute in batches
        for i in range(0, len(records), batch_size):
            batch = records[i:i + batch_size]
            cursor.executemany(query, batch)
            inserted_rows += cursor.rowcount
            print(f"✓ Batch inserted {cursor.rowcount} rows to {schema}.{table_name}")

        conn.commit()
        print(f"✅ Total {inserted_rows} rows inserted to {schema}.{table_name}")
        return inserted_rows

    except psycopg2.Error as e:
        conn.rollback()
        error_msg = f"❌ Database error in {schema}.{table_name}: {str(e)}"
        print(error_msg)
        raise type(e)(error_msg).with_traceback(e.__traceback__)

    except Exception as e:
        conn.rollback()
        error_msg = f"❌ Unexpected error in {schema}.{table_name}: {str(e)}"
        print(error_msg)
        raise

    finally:
        cursor.close()

def run_etl_pipeline(tables_data):
    """Orchestrate the complete ETL pipeline with proper resource management"""
    conn = None
    try:
        conn = get_connection()
        with conn:
            # Process dimension tables
            for table_name, (df, pk_column) in tables_data['dimensions'].items():
                insert_dataframe(df, table_name, conn, pk_column=pk_column)
            
            # Process fact table with special handling
            fact_df = tables_data['fact']['df']
            fact_df_clean = fact_df.replace({np.nan: None, 'NaN': None, '': None})
            insert_dataframe(fact_df_clean, 'fact_table', conn, pk_column=None)

    except Exception as e:
        print(f"🔥 ETL Pipeline Failed: {str(e)}")
        raise
    finally:
        if conn and not conn.closed:
            conn.close()

# Configuration
'''
TABLES_CONFIG = {
    'dimensions': {
        'location_dim': (location_dim, 'location_id'),
        'features_dim': (features_dim, 'feature_id'),
        'property_dim': (property_dim, 'property_id'),
        'owner_dim': (owner_dim, 'owner_id'),
        'date_dim': (date_dim, 'date_id')
    },
    'fact': {
        'df': fact_table
    }
}'''
TABLES_CONFIG = {
    'dimensions': {
        'location_dim': (location_dim, 'location_id'),
        'features_dim': (features_dim, 'feature_id'),
        'property_dim': (property_dim, 'property_id'),
        'owner_dim': (owner_dim, 'owner_id'),
        'date_dim': (date_dim.replace({'month': {'January': 1, 'February': 2, 'March': 3, 
                                               'April': 4, 'May': 5, 'June': 6,
                                               'July': 7, 'August': 8, 'September': 9,
                                               'October': 10, 'November': 11, 'December': 12}}), 
                     'date_id')
    },
    'fact': {
        'df': fact_table
    }
}

# Execute the pipeline
if __name__ == "__main__":
    try:
        run_etl_pipeline(TABLES_CONFIG)
        print("🎉 ETL Pipeline completed successfully!")
    except Exception as e:
        print(f"💥 ETL Pipeline failed: {str(e)}")
        exit(1)

✅ Connected to 'etl_pipeline_db' as etl_user
✓ Batch inserted 0 rows to etl_pipeline_db.location_dim
✓ Batch inserted 0 rows to etl_pipeline_db.location_dim
✓ Batch inserted 0 rows to etl_pipeline_db.location_dim
✅ Total 0 rows inserted to etl_pipeline_db.location_dim
✓ Batch inserted 0 rows to etl_pipeline_db.features_dim
✓ Batch inserted 0 rows to etl_pipeline_db.features_dim
✓ Batch inserted 0 rows to etl_pipeline_db.features_dim
✅ Total 0 rows inserted to etl_pipeline_db.features_dim
✓ Batch inserted 0 rows to etl_pipeline_db.property_dim
✓ Batch inserted 0 rows to etl_pipeline_db.property_dim
✓ Batch inserted 0 rows to etl_pipeline_db.property_dim
✅ Total 0 rows inserted to etl_pipeline_db.property_dim
✓ Batch inserted 0 rows to etl_pipeline_db.owner_dim
✓ Batch inserted 0 rows to etl_pipeline_db.owner_dim
✓ Batch inserted 0 rows to etl_pipeline_db.owner_dim
✅ Total 0 rows inserted to etl_pipeline_db.owner_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✓ Batch inserted 0 rows to etl_pipeline_db.date_dim
✅ Total 0 rows inserted to etl_pipeline_db.date_dim
✓ Batch inserted 1000 rows to etl_pipeline_db.fact_table
✓ Batch inserted 1000 rows to etl_pipeline_db.fact_table
✓ Batch inserted 796 rows to etl_pipeline_db.fact_table
✅ Total 2796 rows inserted to etl_pipeline_db.fact_table
🎉 ETL Pipeline completed successfully!

### Solution 1: Use ON CONFLICT DO NOTHING (PostgreSQL)

In [559]:
def insert_dataframe(df, table_name, conn, schema="etl_pipeline_db"):
    cursor = conn.cursor()
    try:
        columns = list(df.columns)
        values_placeholder = ', '.join(['%s'] * len(columns))
        insert_query = f"""
            INSERT INTO {schema}.{table_name} ({', '.join(columns)})
            VALUES ({values_placeholder})
            ON CONFLICT DO NOTHING
        """
        data = [tuple(x) for x in df.to_numpy()]
        cursor.executemany(insert_query, data)
        conn.commit()
        print(f"✅ Inserted {cursor.rowcount} rows into {schema}.{table_name}")
    except Exception as e:
        conn.rollback()
        print(f"❌ Error inserting into {schema}.{table_name}: {e}")
    finally:
        cursor.close()

###  Solution 2: Upsert (Update existing, insert new)

In [573]:
def insert_dataframe(df, table_name, conn, schema="etl_pipeline_db"):
    cursor = conn.cursor()
    try:
        columns = list(df.columns)
        values_placeholder = ', '.join(['%s'] * len(columns))
        update_set = ', '.join([f"{col} = EXCLUDED.{col}" for col in columns if col != 'location_id'])
        
        insert_query = f"""
            INSERT INTO {schema}.{table_name} ({', '.join(columns)})
            VALUES ({values_placeholder})
            ON CONFLICT (location_id) DO UPDATE SET {update_set}
        """
        data = [tuple(x) for x in df.to_numpy()]
        cursor.executemany(insert_query, data)
        conn.commit()
        print(f"✅ Upserted {cursor.rowcount} rows into {schema}.{table_name}")
    except Exception as e:
        conn.rollback()
        print(f"❌ Error upserting into {schema}.{table_name}: {e}")
    finally:
        cursor.close()

### Solution 3: Truncate and reload (for full refreshes)

In [574]:
def insert_dataframe(df, table_name, conn, schema="etl_pipeline_db"):
    cursor = conn.cursor()
    try:
        # Truncate table first
        cursor.execute(f"TRUNCATE TABLE {schema}.{table_name}")
        
        # Insert fresh data
        columns = list(df.columns)
        values_placeholder = ', '.join(['%s'] * len(columns))
        insert_query = f"""
            INSERT INTO {schema}.{table_name} ({', '.join(columns)})
            VALUES ({values_placeholder})
        """
        data = [tuple(x) for x in df.to_numpy()]
        cursor.executemany(insert_query, data)
        conn.commit()
        print(f"✅ Refreshed {len(data)} rows in {schema}.{table_name}")
    except Exception as e:
        conn.rollback()
        print(f"❌ Error refreshing {schema}.{table_name}: {e}")
    finally:
        cursor.close()

### Solution 4: Filter out existing records

In [575]:
def insert_dataframe(df, table_name, conn, schema="etl_pipeline_db"):
    cursor = conn.cursor()
    try:
        # Get existing IDs
        cursor.execute(f"SELECT location_id FROM {schema}.{table_name}")
        existing_ids = {row[0] for row in cursor.fetchall()}
        
        # Filter new records
        new_records = df[~df['location_id'].isin(existing_ids)]
        
        if not new_records.empty:
            columns = list(new_records.columns)
            values_placeholder = ', '.join(['%s'] * len(columns))
            insert_query = f"""
                INSERT INTO {schema}.{table_name} ({', '.join(columns)})
                VALUES ({values_placeholder})
            """
            data = [tuple(x) for x in new_records.to_numpy()]
            cursor.executemany(insert_query, data)
            conn.commit()
            print(f"✅ Inserted {len(data)} new rows into {schema}.{table_name}")
        else:
            print(f"ℹ️ No new records to insert into {schema}.{table_name}")
    except Exception as e:
        conn.rollback()
        print(f"❌ Error inserting into {schema}.{table_name}: {e}")
    finally:
        cursor.close()

### Solution 5: Filter out existing records and add pk resolutions

In [576]:
def insert_dataframe(df, table_name, conn, schema="etl_pipeline_db", pk_column=None):
    """
    Improved version that handles:
    - Different primary key columns per table
    - NaN values properly
    - Better error reporting
    """
    cursor = conn.cursor()
    try:
        # Clean NaN values
        df = df.replace({np.nan: None})
        
        # Skip empty DataFrames
        if df.empty:
            print(f"ℹ️ No data to insert into {schema}.{table_name}")
            return

        # For tables with known primary keys
        if pk_column:
            # Get existing IDs
            cursor.execute(f"SELECT {pk_column} FROM {schema}.{table_name}")
            existing_ids = {row[0] for row in cursor.fetchall()}
            
            # Filter new records
            new_records = df[~df[pk_column].isin(existing_ids)]
        else:
            new_records = df

        if not new_records.empty:
            columns = list(new_records.columns)
            values_placeholder = ', '.join(['%s'] * len(columns))
            insert_query = f"""
                INSERT INTO {schema}.{table_name} ({', '.join(columns)})
                VALUES ({values_placeholder})
                ON CONFLICT DO NOTHING
            """
            data = [tuple(x) for x in new_records.to_numpy()]
            cursor.executemany(insert_query, data)
            conn.commit()
            print(f"✅ Inserted {cursor.rowcount} rows into {schema}.{table_name}")
        else:
            print(f"ℹ️ No new records to insert into {schema}.{table_name}")
            
    except Exception as e:
        conn.rollback()
        print(f"❌ Error inserting into {schema}.{table_name}: {str(e)}")
        raise
    finally:
        cursor.close()

# Usage Example
import numpy as np

In [577]:
conn = None
try:
    conn = get_connection()
    
    # Define primary key column for each table
    table_pk_map = {
        "location_dim": "location_id",
        "features_dim": "features_id",  # adjust as needed
        "property_dim": "property_id",
        "owner_dim": "owner_id",
        "date_dim": "date_id",
        "fact_table": None  # No deduplication for fact table
    }
    
    with conn:
        insert_dataframe(location_dim, "location_dim", conn, pk_column=table_pk_map["location_dim"])
        insert_dataframe(features_dim, "features_dim", conn, pk_column=table_pk_map["features_dim"])
        insert_dataframe(property_dim, "property_dim", conn, pk_column=table_pk_map["property_dim"])
        insert_dataframe(owner_dim, "owner_dim", conn, pk_column=table_pk_map["owner_dim"])
        insert_dataframe(date_dim, "date_dim", conn, pk_column=table_pk_map["date_dim"])
        
        # Special handling for fact table
        df_fact_clean = fact_table.replace({np.nan: None})
        insert_dataframe(df_fact_clean, "fact_table", conn, pk_column=None)
        
except Exception as e:
    print(f"🔥 Critical error in ETL pipeline: {str(e)}")
    raise
    
finally:
    if conn is not None:
        conn.close()

✅ Connected to 'etl_pipeline_db' as etl_user
ℹ️ No new records to insert into etl_pipeline_db.location_dim
ℹ️ No new records to insert into etl_pipeline_db.features_dim
ℹ️ No new records to insert into etl_pipeline_db.property_dim
ℹ️ No new records to insert into etl_pipeline_db.owner_dim
ℹ️ No new records to insert into etl_pipeline_db.date_dim
✅ Inserted 2796 rows into etl_pipeline_db.fact_table

In [578]:
# Usage Example
conn = None
try:
    conn = get_connection()
    
    # Wrap in transaction for atomicity
    with conn:
        insert_dataframe(location_dim, "location_dim", conn)
        insert_dataframe(features_dim, "features_dim", conn)
        insert_dataframe(property_dim, "property_dim", conn)
        insert_dataframe(owner_dim, "owner_dim", conn)
        insert_dataframe(date_dim, "date_dim", conn)
        insert_dataframe(fact_table, "fact_table", conn)
        
except Exception as e:
    print(f"🔥 Critical error in ETL pipeline: {str(e)}")
finally:
    if conn is not None:
        conn.close()

✅ Connected to 'etl_pipeline_db' as etl_user
✅ Inserted 0 rows into etl_pipeline_db.location_dim
✅ Inserted 0 rows into etl_pipeline_db.features_dim
✅ Inserted 0 rows into etl_pipeline_db.property_dim
✅ Inserted 0 rows into etl_pipeline_db.owner_dim
✅ Inserted 0 rows into etl_pipeline_db.date_dim
✅ Inserted 2796 rows into etl_pipeline_db.fact_table

In [579]:
def insert_dataframe(df, table_name, conn, schema="etl_pipeline_d", batch_size=1000):
    """
    Insert DataFrame into a database table efficiently.
    
    Args:
        df: Pandas DataFrame to insert
        table_name: Target table name
        conn: Active database connection
        schema: Database schema (default: 'etl_pipeline')
        batch_size: Number of rows to insert per batch (default: 1000)
    """
    if df.empty:
        print(f"⚠️ DataFrame for {schema}.{table_name} is empty - nothing to insert")
        return

    cursor = conn.cursor()
    try:
        columns = list(df.columns)
        values_placeholder = ', '.join(['%s'] * len(columns))
        insert_query = f"""
            INSERT INTO {schema}.{table_name} ({', '.join(columns)})
            VALUES ({values_placeholder})
        """
        
        # Convert DataFrame to list of tuples once (more memory efficient)
        data = [tuple(x) for x in df.to_numpy()]
        
        # Insert in batches for better performance
        for i in range(0, len(data), batch_size):
            batch = data[i:i + batch_size]
            cursor.executemany(insert_query, batch)
            conn.commit()
            print(f"✓ Inserted {len(batch)} rows into {schema}.{table_name} (batch {i//batch_size + 1})")
            
        print(f"✅ Successfully inserted {len(data)} total rows into {schema}.{table_name}")
        
    except Exception as e:
        conn.rollback()
        print(f"❌ Error inserting into {schema}.{table_name}: {str(e)}")
        raise  # Re-raise exception after handling
    finally:
        cursor.close()

In [63]:
def load_data_from_csv_to_table(csv_path, table_name_sql):
    import psycopg2
    import pandas as pd
    
    
    # Read CSV
    df = pd.read_csv(csv_path)
    
    # Fix float integers (e.g., 19981130.0 → 19981130)
    df = df.applymap(lambda x: int(x) if isinstance(x, float) and x.is_integer() else x)
    
    # Insert rows
    for row in df.itertuples(index=False, name=None):
        placeholders = ','.join(['%s'] * len(row))
        query = f'INSERT INTO {table_name_sql} VALUES ({placeholders})'
        cursor.execute(query, row)
    
    # Commit changes and clean up
    conn.commit()
    cursor.close()
    conn.close()

# Path to CSV file
# transaction_fact_table_csv_path = r"C:\Users\admin\Desktop\ETL_PIPELINE\data\transaction_fact_table.csv"

# Load data
# load_data_from_csv_to_table(transaction_fact_table_csv_path, 'zipco.transaction_fact_table')

In [64]:
def load_dataframe_to_table(df, table_name, conn):
    """Load a Pandas DataFrame into a Postgres table"""
    cursor = conn.cursor()
    
    columns = list(df.columns)
    insert_sql = sql.SQL("""
        INSERT INTO {table} ({fields})
        VALUES ({placeholders})
        ON CONFLICT DO NOTHING
    """).format(
        table=sql.Identifier(table_name),
        fields=sql.SQL(', ').join(map(sql.Identifier, columns)),
        placeholders=sql.SQL(', ').join(sql.Placeholder() * len(columns))
    )
    
    for row in df.itertuples(index=False, name=None):
        cursor.execute(insert_sql, row)
    
    conn.commit()
    cursor.close()
    print(f"✅ Loaded {len(df)} rows into {table_name}")
print("✅ Function to load dataframe to tables created ")

✅ Function to load dataframe to tables created

# LOADING COMPLETED: [postgresql+psycopg2 OR sqlalchemy+psycopg2 ] 

# TESTING STARTED

In [584]:
# tests/test_nulls.py

def test_nulls(table, column):
    """Test for NULLs in a specific table and column."""
    query = f"SELECT COUNT(*) FROM {table} WHERE {column} IS NULL;"
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute(query)
        count = cur.fetchone()[0]
        print(f"🧪 {column} in {table}: {count} NULL(s)")
        assert count == 0, f"❌ Test failed: {column} in {table} contains NULLs!"
        print(f"✅ Test successful: {column} in {table}")
    finally:
        cur.close()
        conn.close()

# --- Example Correct Tests ---

# Testing columns in fact_table
test_nulls("fact_table", "last_sale_price")
test_nulls("fact_table", "property_taxes")

# Testing columns in location_dim
test_nulls("location_dim", "address_line1")
test_nulls("location_dim", "city")

✅ Connected to 'etl_pipeline_db' as etl_user

UndefinedTable: relation "fact_table" does not exist
LINE 1: SELECT COUNT(*) FROM fact_table WHERE last_sale_price IS NUL...
                             ^

In [228]:
def configure_logging():
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(Config.DATA_PATHS['logs'] / 'etl.log'),
            logging.StreamHandler()
        ]
    )
    return logging
print("Logger: ")

Logger:

In [229]:
def main():
    configure_logging()
    logger = logging.getLogger(__name__)
    logger.info("Starting ETL process...")

    # Initialize
    transformer = PropertyTransformer()
    loader = DatabaseLoader()
    logger = logging.getLogger(__name__)
    logger.info("Starting ETL process...")

    # Load raw data
    logger.info("Loading raw data...")
    propertyrecords_df = load_raw_data()
    logger.info(f"Raw data loaded with {len(propertyrecords_df)} records.")
    
    # Preprocess data
    logger.info("Preprocessing data...")
    propertyrecords_df = transformer.preprocess_data(propertyrecords_df)
    logger.info(f"Data preprocessed with {len(propertyrecords_df)} records.")     
    
    # Transform data
    logger.info("Transforming data...")

    # Create dimensions
    dimensions = transformer.create_dimensions(propertyrecords_df)
    logger.info("Dimensions created.")

    # Save dimensions to CSV and load to Postgres
    for name, df in dimensions.items():
        loader.save_to_csv(df, Config.DATA_PATHS['dimensions'] / f"{name}.csv")
        loader.load_to_postgres(df, name)
        logger.info(f"Dimension {name} saved and loaded to Postgres.")

    # Create fact table
    logger.info("Creating fact table...")
    facts = transformer.create_fact_table(propertyrecords_df)

    # Database operations should be done at the end
    logger.info("Performing database operations...")
    loader.create_postgresql_connection()
    logger.info("PostgreSQL connection created.")
    loader.create_schema()
    logger.info("Schema created.")
    loader.create_database()
    logger.info("Database created.")

    # create tables
    logger.info("Creating tables...")
    loader.create_tables()
    logger.info("Tables created.")

    # create indexes
    logger.info("Creating indexes...")
    loader.create_indexes()
    logger.info("Indexes created.")


if __name__ == "__main__":
    main()

NameError: name 'logging' is not defined

# RUNNING queries

In [204]:
# utils/query_runner.py

def run_query(query, fetch=True):
    """Run a SQL query on the database."""
    conn = get_db_connection()
    cur = conn.cursor()
    try:
        cur.execute(query)
        if fetch:
            results = cur.fetchall()
            return results
        else:
            conn.commit()
            return None
    finally:
        cur.close()
        conn.close()
print("✅ function to 'run_query' is loaded")

✅ function to 'run_query' is loaded

In [205]:
# Select 5 rows from location_dim
rows = run_query("SELECT * FROM location_dim LIMIT 5;")
for row in rows:
    print(row)

(1, '801 Plate St', 'Rochester', 'MI', '48307', 'Oakland', 42.687461, -83.125512, 'OAKLAND COUNTY CONDOMINIUM', 'KI')
(2, '11328 Van Buren St NE', 'Minneapolis', 'MN', '55434', 'Anoka', 45.17613, -93.250083, 'RIFE ESTATES', 'Unknown')
(3, '1148 S Ventura Cir', 'Aurora', 'CO', '80017', 'Arapahoe', 39.695339, -104.776629, 'DISCOVERY AT QUAIL RUN CONDOS PHS 6 THRU', 'PUD')
(4, '135 Bordentown Crosswicks Rd', 'Crosswicks', 'NJ', '8515', 'Burlington', 40.144733, -74.66356, 'Unknown', 'PVD2')
(5, '7700 E Princess Dr', 'Scottsdale', 'AZ', '85255', 'Maricopa', 33.645192, -111.913378, 'CROWN POINT', 'M-H')

###  Property Count by Status (Owner Occupied)

In [36]:
SELECT 
    o.owner_occupied,
    COUNT(*) AS property_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 1) AS percentage
FROM 
    etl_pipeline.owner_dim o
GROUP BY 
    o.owner_occupied
ORDER BY 
    property_count DESC;

IndentationError: unexpected indent (<ipython-input-36-cdb9cc77c63c>, line 2)

### Top 10 Most Expensive Listings

In [37]:
SELECT 
    l.formatted_address,
    l.zip_code,
    p.property_type,
    p.bedrooms,
    p.bathrooms,
    p.square_footage,
    ROUND(f.price_per_sqft * p.square_footage, 2) AS estimated_price,
    f.price_per_sqft
FROM 
    etl_pipeline.property_facts f
JOIN 
    etl_pipeline.location_dim l ON f.property_id = l.property_id
JOIN 
    etl_pipeline.property_dim p ON f.property_id = p.property_id
WHERE 
    f.price_per_sqft IS NOT NULL 
    AND p.square_footage IS NOT NULL
ORDER BY 
    estimated_price DESC
LIMIT 10;

IndentationError: unexpected indent (<ipython-input-37-aaff3e181db4>, line 2)

### Price Distribution by Property Type

In [38]:
SELECT 
    p.property_type,
    ROUND(AVG(f.price_per_sqft * p.square_footage), 2) AS avg_price,
    ROUND(MIN(f.price_per_sqft * p.square_footage), 2) AS min_price,
    ROUND(MAX(f.price_per_sqft * p.square_footage), 2) AS max_price,
    COUNT(*) AS property_count
FROM 
    etl_pipeline.property_facts f
JOIN 
    etl_pipeline.property_dim p ON f.property_id = p.property_id
WHERE 
    f.price_per_sqft IS NOT NULL 
    AND p.square_footage IS NOT NULL
GROUP BY 
    p.property_type
ORDER BY 
    avg_price DESC;

IndentationError: unexpected indent (<ipython-input-38-0ec61f99d5fd>, line 2)

### Tax Assessment Analysis

In [39]:
SELECT 
    l.zip_code,
    ROUND(AVG(t.assessed_value), 2) AS avg_assessment,
    ROUND(AVG(f.price_per_sqft * p.square_footage), 2) AS avg_market_price,
    ROUND(AVG(t.assessed_value) * 100.0 / NULLIF(AVG(f.price_per_sqft * p.square_footage), 0), 1) AS assessment_ratio
FROM 
    etl_pipeline.tax_assessments t
JOIN 
    etl_pipeline.property_facts f ON t.property_id = f.property_id
JOIN 
    etl_pipeline.property_dim p ON t.property_id = p.property_id
JOIN 
    etl_pipeline.location_dim l ON t.property_id = l.property_id
WHERE 
    t.assessed_value IS NOT NULL
    AND f.price_per_sqft IS NOT NULL
    AND p.square_footage IS NOT NULL
GROUP BY 
    l.zip_code
HAVING 
    COUNT(*) > 5
ORDER BY 
    assessment_ratio DESC;

IndentationError: unexpected indent (<ipython-input-39-57297e479ee4>, line 2)

### Recent Sales Activity

In [40]:
SELECT 
    DATE_TRUNC('month', h.event_date) AS month,
    COUNT(*) AS sales_count,
    ROUND(AVG(h.price), 2) AS avg_sale_price,
    ROUND(MIN(h.price), 2) AS min_sale_price,
    ROUND(MAX(h.price), 2) AS max_sale_price
FROM 
    etl_pipeline.property_history h
WHERE 
    h.event_type = 'Sale'
    AND h.event_date >= CURRENT_DATE - INTERVAL '12 months'
GROUP BY 
    DATE_TRUNC('month', h.event_date)
ORDER BY 
    month DESC;

IndentationError: unexpected indent (<ipython-input-40-4a5af91f935b>, line 2)

## 13. Orchestration (Airflow, Cron, Event Triggers)

In [81]:
# This would be implemented in separate files, but here's the plan:

"""
### Airflow DAG (would be in dags/property_etl.py)
1. Schedule: Daily at 2AM
2. Tasks:
   - extract_property_data (PythonOperator to make API call)
   - validate_raw_data (PythonOperator to check data quality)
   - transform_data (PythonOperator to process data)
   - load_to_postgres (PythonOperator to load to DB)
   - generate_reports (PythonOperator to create BI reports)
3. Error handling and retries
4. Slack notifications on failure/success

### Cron Jobs (for simpler scheduling)
- Basic data backup: 0 3 * * * /path/to/backup_script.sh

### Event Triggers
- AWS Lambda or similar for:
  - New property listings (webhook from source system)
  - Data quality alerts (trigger reprocessing)
"""

'\n### Airflow DAG (would be in dags/property_etl.py)\n1. Schedule: Daily at 2AM\n2. Tasks:\n   - extract_property_data (PythonOperator to make API call)\n   - validate_raw_data (PythonOperator to check data quality)\n   - transform_data (PythonOperator to process data)\n   - load_to_postgres (PythonOperator to load to DB)\n   - generate_reports (PythonOperator to create BI reports)\n3. Error handling and retries\n4. Slack notifications on failure/success\n\n### Cron Jobs (for simpler scheduling)\n- Basic data backup: 0 3 * * * /path/to/backup_script.sh\n\n### Event Triggers\n- AWS Lambda or similar for:\n  - New property listings (webhook from source system)\n  - Data quality alerts (trigger reprocessing)\n'

## 14. Error Tracking and Alerting

In [82]:
"""
### Implementation Plan:
1. Sentry.io integration for error tracking
2. Slack webhooks for alerts on:
   - Failed API calls
   - Data quality issues (nulls, outliers)
   - ETL job failures
3. Airflow email/SMS alerts
4. Log all operations to files in logs/ with rotation
5. Data validation checks:
   - Row counts between steps
   - Null checks on critical fields
   - Data type validation
"""

'\n### Implementation Plan:\n1. Sentry.io integration for error tracking\n2. Slack webhooks for alerts on:\n   - Failed API calls\n   - Data quality issues (nulls, outliers)\n   - ETL job failures\n3. Airflow email/SMS alerts\n4. Log all operations to files in logs/ with rotation\n5. Data validation checks:\n   - Row counts between steps\n   - Null checks on critical fields\n   - Data type validation\n'

## 15. BI Dashboards, Reports and ML Models

In [83]:

"""
### BI Dashboards (Power BI/Tableau/Metabase):
1. Property Market Overview:
   - Price distribution by property type
   - Inventory by location
   - Price trends over time

2. Investment Analysis:
   - ROI by property type/location
   - Tax assessment trends
   - Price per sqft heatmap

### Reports:
1. Weekly/Monthly market reports (PDF/Excel)
2. Automated email digests of key metrics

### ML Models:
1. Price prediction model (scikit-learn/TensorFlow)
2. Property recommendation engine
3. Anomaly detection for fraudulent listings
"""

'\n### BI Dashboards (Power BI/Tableau/Metabase):\n1. Property Market Overview:\n   - Price distribution by property type\n   - Inventory by location\n   - Price trends over time\n\n2. Investment Analysis:\n   - ROI by property type/location\n   - Tax assessment trends\n   - Price per sqft heatmap\n\n### Reports:\n1. Weekly/Monthly market reports (PDF/Excel)\n2. Automated email digests of key metrics\n\n### ML Models:\n1. Price prediction model (scikit-learn/TensorFlow)\n2. Property recommendation engine\n3. Anomaly detection for fraudulent listings\n'

In [84]:
print("ETL pipeline design complete!")

ETL pipeline design complete!

In [85]:
Key Features of This Implementation:
    Complete ETL Pipeline: From data generation to database loading
    Modular Structure: Each step is clearly separated
    Data Quality Checks: Null handling, type conversion, validation
    Dimension/Fact Tables: Proper star schema implementation
    PostgreSQL Integration: With schema creation and data loading
    Orchestration Planning: Airflow, cron, and event triggers
    Monitoring/Alerting: Error tracking system design
    BI/ML Integration: Roadmap for analytics

How to Use:
    Run each cell sequentially in Jupyter
    For PostgreSQL connection, update the credentials
    The script creates all necessary files and folders
    Sample data is generated and processed through the pipeline

Note: For a production system, you would want to:
    Break this into separate Python files
    Add more robust error handling
    Implement proper logging
    Add configuration management
    Containerize with Docker
    Add more comprehensive data validation

SyntaxError: invalid syntax (<ipython-input-85-22d73b58481d>, line 1)

# PowerBI Dashboard Solution

In [ ]:
// Power BI Query (M Language)
let
    // Connect to PostgreSQL
    Source = PostgreSQL.Database(
        "your-server-name", 
        "property_db",
        [CreateNavigationProperties=false]
    ),
    
    // Import dimension tables
    property_dim = Source{[Schema="etl_pipeline",Item="property_dim"]}[Data],
    location_dim = Source{[Schema="etl_pipeline",Item="location_dim"]}[Data],
    owner_dim = Source{[Schema="etl_pipeline",Item="owner_dim"]}[Data],
    tax_dim = Source{[Schema="etl_pipeline",Item="tax_dim"]}[Data],
    
    // Import fact table
    facts = Source{[Schema="etl_pipeline",Item="property_facts"]}[Data],
    
    // Create relationships
    final_data = Table.NestedJoin(facts, "property_id", property_dim, "property_id", "property", JoinKind.LeftOuter),
    final_data_expanded = Table.ExpandTableColumn(final_data, "property", {"property_type", "bedrooms", "bathrooms"}, {"property_type", "bedrooms", "bathrooms"})
in
    final_data_expanded

# DAX Measures for KPIs

In [ ]:
// Power BI DAX Measures
Avg Price per SqFt = AVERAGE(facts[price_per_sqft])

Price Trend = 
VAR CurrentDate = MAX(history[event_date])
VAR PriorDate = DATEADD(history[event_date], -12, MONTH)
RETURN
    CALCULATE(
        AVERAGE(history[price]),
        FILTER(
            ALL(history),
            history[event_date] >= PriorDate && 
            history[event_date] <= CurrentDate
        )
    )

Inventory Count = COUNTROWS(property_dim)

Tax Assessment Ratio = 
DIVIDE(
    AVERAGE(tax_dim[assessed_value]),
    AVERAGE(facts[price_per_sqft] * property_dim[square_footage]),
    0
)

# Tableau Dashboard Solution

In [ ]:
A. Data Connection
# Tableau Prep flow example
- Input: PostgreSQL connection
- Clean: Handle nulls in price/sqft
- Output: Published Data Source

B. Key Worksheets
Visualization	Mark Type	Encoding
Price Heatmap	Map	ZIP codes colored by avg price
Inventory Dashboard	Bar Chart	Property type by count
Price vs. SqFt	Scatter Plot	X: SqFt, Y: Price, Color: Prop Type
Monthly Sales Trends	Area Chart	Date by sales volume


C. Tableau Calculated Fields
// Avg Price per Bedroom
{FIXED [bedrooms]: AVG([price_per_sqft]*[square_footage])}

// Price Premium
[price_per_sqft] - LOOKUP(AVG([price_per_sqft]), -1)

// Days on Market
DATEDIFF('day', [list_date], [sale_date])

D. Dashboard Layout
1. **Top Section**:
   - KPIs: Total Inventory, Avg Price, Sold This Month
   - Filters Panel

2. **Middle Section**:
   - Left: Map Visualization
   - Right: Price Distribution by Type

3. **Bottom Section**:
   - Top Performers Table
   - Trend Analysis

In [ ]:
#!/usr/bin/env python3
"""
Property Data ETL Pipeline
Run on schedule with Airflow or as standalone script
"""

import pandas as pd
import numpy as np
import logging
from datetime import datetime, timedelta
from pathlib import Path
import smtplib
from email.mime.text import MIMEText
import json
import psycopg2
from sqlalchemy import create_engine
import sys
from airflow import DAG
from airflow.operators.python import PythonOperator

# Configuration
CONFIG = {
    "data_paths": {
        "raw": "data/raw/propertyrecords.json",
        "processed": "data/processed/",
        "dimensions": "data/dimensions/",
        "facts": "data/facts/"
    },
    "db": {
        "host": "localhost",
        "database": "property_db",
        "user": "postgres",
        "password": "postgres",
        "port": "5432"
    },
    "email": {
        "alerts_to": "admin@example.com",
        "smtp_server": "smtp.example.com",
        "smtp_port": 587,
        "smtp_user": "alerts@example.com",
        "smtp_pass": "yourpassword"
    },
    "schedule": "@daily"  # Airflow schedule interval
}

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('logs/etl_pipeline.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

class ETLError(Exception):
    """Custom exception for ETL failures"""
    pass

def send_alert(subject, message):
    """Send email alert on failure"""
    msg = MIMEText(message)
    msg['Subject'] = f"[ETL Alert] {subject}"
    msg['From'] = CONFIG['email']['smtp_user']
    msg['To'] = CONFIG['email']['alerts_to']
    
    try:
        with smtplib.SMTP(CONFIG['email']['smtp_server'], CONFIG['email']['smtp_port']) as server:
            server.starttls()
            server.login(CONFIG['email']['smtp_user'], CONFIG['email']['smtp_pass'])
            server.send_message(msg)
    except Exception as e:
        logger.error(f"Failed to send alert email: {str(e)}")

def create_folders():
    """Ensure all required directories exist"""
    for path in CONFIG['data_paths'].values():
        if path.endswith('/'):
            Path(path).mkdir(parents=True, exist_ok=True)
    Path("logs").mkdir(exist_ok=True)

def load_raw_data():
    """Load and validate raw JSON data"""
    try:
        raw_path = Path(CONFIG['data_paths']['raw'])
        with open(raw_path) as f:
            data = json.load(f)
        df = pd.DataFrame(data)
        logger.info(f"Loaded {len(df)} raw records from {raw_path}")
        return df
    except Exception as e:
        error_msg = f"Failed to load raw data: {str(e)}"
        logger.error(error_msg)
        send_alert("Data Load Failed", error_msg)
        raise ETLError(error_msg)

def transform_data(raw_df):
    """Transform raw data into dimensional model"""
    try:
        # Your transformation logic here
        logger.info("Data transformation completed")
        return {
            "property_dim": pd.DataFrame(),  # Replace with actual transforms
            "location_dim": pd.DataFrame(),
            "owner_dim": pd.DataFrame(),
            "tax_dim": pd.DataFrame(),
            "property_facts": pd.DataFrame()
        }
    except Exception as e:
        error_msg = f"Transformation failed: {str(e)}"
        logger.error(error_msg)
        send_alert("Transformation Failed", error_msg)
        raise ETLError(error_msg)

def load_to_postgres(dataframes):
    """Load dimension tables to PostgreSQL"""
    try:
        engine = create_engine(
            f"postgresql+psycopg2://{CONFIG['db']['user']}:{CONFIG['db']['password']}@"
            f"{CONFIG['db']['host']}:{CONFIG['db']['port']}/{CONFIG['db']['database']}"
        )
        
        with engine.connect() as conn:
            for table_name, df in dataframes.items():
                df.to_sql(
                    table_name,
                    conn,
                    schema='etl_pipeline',
                    if_exists='replace',
                    index=False
                )
                logger.info(f"Loaded {len(df)} records to {table_name}")
        
        logger.info("Database load completed successfully")
    except Exception as e:
        error_msg = f"Database load failed: {str(e)}"
        logger.error(error_msg)
        send_alert("Database Load Failed", error_msg)
        raise ETLError(error_msg)

def run_etl():
    """Main ETL workflow"""
    try:
        logger.info("Starting ETL pipeline")
        create_folders()
        
        # Extract
        raw_data = load_raw_data()
        
        # Transform
        transformed_data = transform_data(raw_data)
        
        # Load
        load_to_postgres(transformed_data)
        
        logger.info("ETL pipeline completed successfully")
        return True
    except ETLError:
        logger.error("ETL pipeline failed")
        return False

# Airflow DAG configuration
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    'property_data_etl',
    default_args=default_args,
    description='Property Data ETL Pipeline',
    schedule_interval=CONFIG['schedule'],
    start_date=datetime(2023, 1, 1),
    catchup=False,
    tags=['real_estate']
)

etl_task = PythonOperator(
    task_id='run_property_etl',
    python_callable=run_etl,
    dag=dag
)

if __name__ == "__main__":
    # Run as standalone script if not executed by Airflow
    success = run_etl()
    sys.exit(0 if success else 1)